### ISSUE TITLE
Tap-to-pay crash with Firebase's RemoteConfig

### ISSUE THREAD

**Issue by GhulJr** [stripe/stripe-terminal-android#323] opened 2023-05-16 14:10 UTC
Hello! c:

## Summary
We use RemoteConfig very early in the app's lifecycle to compare several values. For sure it is called before Stripe Terminal API is initialized. When I try to discover `LocalMobile` mentioned below. It looks like initialising `FirebaseApp` in our app affects Stripe Terminal API behaviour. It works fine when we don't use any Firebase API.

## Logs
I replaced our app's names. `RemoteConfigManager` is our inner class that mainly calls `FirebaseRemoteConfig.getInstance()` underneath.

> FATAL EXCEPTION: main
                                                                                                    Process: com.stripe.cots.aidlservice, PID: 19536
                                                                                                    java.lang.RuntimeException: Unable to create application com.example.App: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.stripe.cots.aidlservice. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6776)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7884)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.stripe.cots.aidlservice. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:179)
                                                                                                    	at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(FirebaseRemoteConfig.java:80)
                                                                                                    	at com.example.tool.config.RemoteConfigManager.<init>(RemoteConfigManager.kt:26)
                                                                                                    	at com.example.DaggerApp_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerApp_HiltComponents_SingletonC.java:1211)
                                                                                                    	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                                                                    	at com.exampleDaggerApp_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerApp_HiltComponents_SingletonC.java:1208)
                                                                                                    	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                                                                    	at com.example.DaggerApp_HiltComponents_SingletonC$SingletonCImpl.injectApp2(DaggerApp_HiltComponents_SingletonC.java:1188)
                                                                                                    	at com.example.DaggerApp_HiltComponents_SingletonC$SingletonCImpl.injectApp(DaggerApp_HiltComponents_SingletonC.java:1168)
                                                                                                    	at com.example.Hilt_App.hiltInternalInject(Hilt_App.java:51)
                                                                                                    	at com.example.Hilt_App.onCreate(Hilt_App.java:42)
                                                                                                    	at com.example.App.onCreate(App.kt:27)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6771)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7884) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
## Code to reproduce
1. Call `FirebaseRemoteConfig.getInstance()` before terminal.
2. Initialise Terminal SDK 
```
Terminal.initTerminal(
                context = applicationContext,
                logLevel = if (BuildConfig.DEBUG) LogLevel.VERBOSE else LogLevel.NONE,
                tokenProvider = connectWithTokenProvider,
                listener = this
)
```
3. Ensure permissions
4. Discover readers
```
val discoverConfig = DiscoveryConfiguration(
        timeout = 10,
        discoveryMethod = DiscoveryMethod.LOCAL_MOBILE,
        isSimulated = false
)
discoverCancelable = Terminal.getInstance().discoverReaders(
            config = discoverConfig,
            discoveryListener = this,
            callback = discoverCallback
 )
```

## Android version
Google Pixel 5 API 33 (Android 13)

## Impacted devices (Android devices or readers)
Tap-to-Pay's local mobile reader.

## SDK version

`com.stripe:stripeterminal` and `com.stripe:stripeterminal-localmobile`- `2.19.0`, `2.20.0` and `2.20.1`
`com.google.firebase:firebase-bom` - `30.3.1` and `32.0.0`

## Other information
If you have any doubts just let me know 😉.

**Comment by htcardone** [comment] 2023-05-17 18:58
Same issue here. Tested with 2.20.1 on a Samsung Galaxy S10e (Android 12)

**Comment by rv-stripe** [comment] 2023-05-18 18:40
Hey -- we've seen similar issues before to this that have been resolved by a gradle clean.
I believe this could be related to Dagger/Hilt's caching after an update.
Could you give this another try with a clean build and let me know if that resolves the issue for you?

**Comment by GhulJr** [comment] 2023-05-23 08:18
Hello, I face the same issue after clean build / invalidating caches.

**Comment by Ekalips** [comment] 2023-07-17 09:52
Getting the same issue on the app initialisation when I try to invoke `Firebase.getInstance(context)`. 

```
java.lang.RuntimeException: Unable to create application com.pepperhq.tenants.tenantname.TenantApplication: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.stripe.cots.aidlservice. Make sure to call FirebaseApp.initializeApp(Context) first.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6810)
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7918)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

I believe it's happening because local-mobile reader tries to spin off a separate process that also invokes `OurApplication.onCreate` that, in our case, initialises Firebase Analytics, and it fails to init because that process doesn't have Firebase initialiser services (expected) in it thus doesn't have Firebase initialised. 

Not sure if it could be fixed by Stripe, but Stripe could help us figure out a way to check if the process we are running in is indeed stripe's process and it shouldn't try to init main app's things.

**Comment by chr-stripe** [comment] 2023-11-10 01:42
> I believe it's happening because local-mobile reader tries to spin off a separate process that also invokes `OurApplication.onCreate` that, in our case, initialises Firebase Analytics, and it fails to init because that process doesn't have Firebase initialiser services (expected) in it thus doesn't have Firebase initialised.

That seems to be correct. The Firebase documentation [^1] states that it should only be initialized in the main application process:

> Any `FirebaseApp` initialization must occur only in the main process of the app. Use of Firebase in processes other than the main process is not supported and will likely cause problems related to resource contention.

You will have to check in your `Application` subclass which process it is currently being created in, and avoid any further initialization if it is not the main process. This StackOverflow answer seems to be pretty comprehensive in fetching the current process name: https://stackoverflow.com/a/55842542

To check if you're in the main process, simply verify that the process name is equal to your application's package name. If it isn't, then you are in a separate process and can skip initialization:

```kotlin
class OurApplication : Application() {
    override fun onCreate() {
        val isMainProcess = getProcessName() == packageName
        if (!isMainProcess) return

        // Proceed with app initialization
    }
}
```

We will explore ways to make detection of the localmobile process easier in future versions.

[^1]: https://firebase.google.com/docs/reference/android/com/google/firebase/FirebaseApp

**Closed by chr-stripe** 2023-11-10 01:42 UTC
Labels: integration, Tap to Pay

**Comment by Ekalips** [comment] 2023-11-10 08:38
I can confirm that the provided workaround/fix works, we've already tested it on live devices. 

Probably one thing to ask is for Stripe to describe this behaviour in their docs, so devs wouldn't be caught off guard.

**Comment by Mahdi-Rida** [comment] 2024-09-23 19:13
Hello, Thank you for your help, i did exactly what you mentioned above, but am still getting this : onFailure: Cannot get readers 11: com.stripe.stripeterminal.external.models.TerminalException: Contactless transaction failed com.stripe.core.aidlrpc.AidlRpcException: Service never connected.

**Comment by chr-stripe** [comment] 2025-05-16 20:39
I'm happy to report that in version 4.4.0 of the Tap to Pay on Android SDK, we now have a `TapToPay.isInTapToPayProcess()` method that you can call from your integration to determine if you need to skip Application initialization. See our [public documentation](https://docs.stripe.com/terminal/payments/connect-reader?terminal-sdk-platform=android&reader-type=tap-to-pay#initialize) for more details on this.
