### ISSUE TITLE
Invalid api key provided: null

### ISSUE THREAD

**Issue by anton8900** [stripe/stripe-terminal-android#35] opened 2019-05-16 09:19 UTC
It throws this error "Invalid api key provided: null". Than i turn off reader, wifi and bluetooth on android and reconnect reader again and all begin to work. I have some problems with wifi when connect reader but when android was already connected to wifi it continue to throw this error untill i reconnected all

**Comment by anton8900** [comment] 2019-05-16 09:23
And even restarting of app was not enough to make it work

**Comment by anton8900** [comment] 2019-05-16 10:33
I think that if key null it should to use TokenProvider and try to get key again

**Comment by ball1008** [comment] 2019-09-04 13:20
Having the same issue.  Any resolution to this issue?

**Comment by bg-stripe** [comment] 2019-09-05 00:11
Hi – responding here to your recent support ticket @ball1008 . 

It looks like you're getting a 400 when creating the PaymentIntent on your backend, due to a malformed request. Looks like you're POST'ing with a single `intent=pi_{XYZ}` parameter to create the PaymentIntent. For more information on creating a PaymentIntent for Terminal on your server, see our docs:

https://stripe.com/docs/terminal/payments#create-server-side

@anton8900 – sorry for the late reply! Hopefully you've resolved your issue now – not sure if it's related to @ball1008 . Let us know if you're having any problems with your integration – and please email support-terminal@stripe.com for integration help in the future!

**Comment by ball1008** [comment] 2019-09-05 01:43
Hi Ben,

I am not getting 400 when creating intents.  
here is  my code to create intents:

Parse.Cloud.define("stripeTerminalCreateIntent", (request)=>{
                   console.log("CLOUDCODE:" + request.params.data);

                   return Parse.Cloud.httpRequest({

                                           method:"POST",
                                           params: {amount: request.params.amount, currency: "usd",
                                                    capture_method: "manual"},

                                           url: "https://" + STRIPE_SECRET_KEY_POS + ':@' + 'api.stripe.com/v1' + "/payment_intents?payment_method_types[]=card_present"

                                           }).then((httpResponse) => {
                                           return httpResponse.text;
                                           },
                                           (error) => {
                                            console.error('Request failed with response code ' + error.message);
                                            throw new Parse.Error(error.code,error.message);
                                           });

                   });


This always returns an intent.  I can also retrieve the intent and client secret.  I also successfully call collectPaymentMethod, insert my test card into my reader and get an intent returned.  The issue occurs when I call processPayment with the intent.  It errors with Invalid API keys nullI.

Jen

**Comment by bg-stripe** [comment] 2019-09-05 02:03
Ah ok – possible I was looking at the wrong Stripe account's logs. Could you share the ID of an example PaymentIntent, one that you've attempted to call `processPayment` with?

If you could share the logs from the SDK as well, with your Terminal instance's logLevel set to verbose, that would be very helpful!

`Terminal.initTerminal(getApplicationContext(), LogLevel.VERBOSE...`

Thanks!

**Comment by ball1008** [comment] 2019-09-05 11:50
Hi Ben,

I changed my retrieve method to use Stripe Terminal sdks on Android so I now get the Invalid API Keys null error when calling retrievePaymentIntent.  Here is my method:

private void retrieveIntent(String clientSecret, String intent){
    Terminal.getInstance().retrievePaymentIntent(clientSecret,
            new PaymentIntentCallback() {
                @Override
                public void onSuccess(PaymentIntent paymentIntent) {
                    // Placeholder for collecting a payment method with paymentIntent
                    getPaymentMethod(paymentIntent);
                    Toast.makeText(_context, paymentIntent.toString(), Toast.LENGTH_LONG).show();
                }

                @Override
                public void onFailure(TerminalException exception) {
                    // Placeholder for handling exception
                    Toast.makeText(_context, exception.getLocalizedMessage(), Toast.LENGTH_LONG).show();
                }
            });
}
The PI id created successfully is  pi_1FFJHZChWd7ullUSee3WP9uS.  
If I change the retrieve method to call from my server, it returns successfully as does collect payment method.  The processPayment function then gets the error.

Jen

**Comment by chander-stripe** [comment] 2020-03-30 23:47
Could you write in to https://support.stripe.com/contact?
The team there can help you out!

Please include the following details when you write in:
1. The SDK version you are on
2. Any errors you see in Logcat
3. Is this on simulated reader or physical reader
4. Reproduction steps

Going to close this as Github Issues should be reserved for SDK feature requests or bugs.
Thanks!

**Closed by chander-stripe** 2020-03-30 23:47 UTC
