### ISSUE TITLE
Unhandled Exception Crashing App with Error "TerminalException: failed to connect to"

### ISSUE THREAD

**Issue by Thamizhan** [stripe/stripe-terminal-android#275] opened 2022-11-29 10:22 UTC
## Summary
App crash with "TerminalException: failed to connect to" When smart reader is switched off while collect payment is in progress.

## Code to reproduce
`Terminal.getInstance().collectPaymentMethod(paymentIntent, callback);`
When Amount is showing on reader swiftch off the reader.

## Android version
Android 12 and 13

## Impacted devices (Android devices or readers)
Smart reader.

## SDK version
2.16.0

## Other information
Crash Log:
> FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.***.***.**, PID: 8159
    com.stripe.stripeterminal.external.models.TerminalException: failed to connect to 192-168-0-185.g7aqrjnfrznc3vc4utko.device.stripe-terminal-local-reader.net/192.168.0.185 (port 4443) from /10.0.2.16 (port 47270) after 10000ms
    	at com.stripe.stripeterminal.internal.common.remotereadercontrollers.CrpcResponseExtensions.withJackrabbitResponse(CrpcResponseExtensions.kt:23)
    	at com.stripe.stripeterminal.internal.common.remotereadercontrollers.IpReaderController$cancelPaymentMethodCollect$1.invokeSuspend(IpReaderController.kt:334)
    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4268ae7, Dispatchers.IO]
    Caused by: java.net.SocketTimeoutException: failed to connect to 192-168-0-185.g7aqrjnfrznc3vc4utko.device.stripe-terminal-local-reader.net/192.168.0.185 (port 4443) from /10.0.2.16 (port 47270) after 10000ms
    	at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
    	at libcore.io.IoBridge.connect(IoBridge.java:179)
    	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
    	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
    	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
    	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
    	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
    	at java.net.Socket.connect(Socket.java:646)
    	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
    	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
    	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
    	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
    	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
    	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
    	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    	at com.stripe.stripeterminal.internal.common.crpc.DistributedTracingInterceptor.intercept(DistributedTracingInterceptor.kt:21)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
    	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
    	at com.stripe.core.crpcclient.CrpcClient.execute(CrpcClient.kt:39)
    	at com.stripe.core.crpcclient.CrpcClient.blockingPost(CrpcClient.kt:94)
    	at com.stripe.proto.api.sdk.JackRabbitApi.cancelCollectPaymentMethod(JackRabbitApi.kt:128)
 E  	at com.stripe.stripeterminal.internal.common.remotereadercontrollers.IpReaderController$cancelCollectPaymentMethod$1.invoke(IpReaderController.kt:198)
    	at com.stripe.stripeterminal.internal.common.remotereadercontrollers.IpReaderController$cancelCollectPaymentMethod$1.invoke(IpReaderController.kt:197)
    	at com.stripe.stripeterminal.internal.common.remotereadercontrollers.IpReaderController$cancelPaymentMethodCollect$1.invokeSuspend(IpReaderController.kt:333)

**Comment by chr-stripe** [comment] 2022-12-01 18:25
Hi @Thamizhan, thanks for the detailed report!

Just to confirm, is this exception is being delivered to you through the `onFailure()` method in your specified `callback`, or is it being thrown somewhere that you cannot catch it?

**Comment by Thamizhan** [comment] 2022-12-02 04:07
Hi @chr-stripe 
Its thrown where we can't catch in our code. It's crashing the app and the stacktrace also show no files included in our project.

**Comment by chr-stripe** [comment] 2022-12-09 03:58
Got it. We're able to reproduce this internally and looking into how to properly handle this case.

**Comment by alanjhughes** [comment] 2022-12-11 21:56
We are also having this issue but when the device is on. We updated to 2.16.0 4 days ago and since then have had 200-plus incidents of this exception. Is does not cause a crash, instead the payment process is stuck.

We use the terminal in a self service kiosk context so when this happens the ui appears frozen until our inactivity timer is triggered and we cancel the process, but this also causes strange behaviour where the terminal continues to request a payment instead of clearing when the payment process is cancelled.

Restarting the app solves it temporarily and then the issue starts to present again until it gets to a point where it happens on every attempt. 

The only change involving the terminal in this update was the bump from 2.13.0 to 2.16.0. The implementation remains the same. It was rolled out only on three devices and is occurring on all three. All other active sites on 2.13.0 are working without issue.

**Comment by billfinn-stripe** [comment] 2022-12-12 17:25
Hi @alanjhughes -- thanks for the details. This sounds like it may be a separate issue. Would you mind creating a new Github issue, include the serial numbers for the readers where you are seeing this issue, and approximate time frame when the issue occurred? That will allow us to search the logs in our backend to troubleshoot what's going on.

**Comment by billfinn-stripe** [comment] 2023-01-04 18:29
@Thamizhan -- just wanted to provide an update here -- we are planning on releasing a fix for this issue in our end of January release.

**Comment by billfinn-stripe** [comment] 2023-03-07 22:40
@Thamizhan -- this issue was fixed in 2.17.0 (and 2.17.1). We are releasing 2.18.0 in the upcoming days, so you can wait for it and upgrade to 2.18.0 or upgrade to 2.17.1 now.

**Closed by billfinn-stripe** 2023-03-07 22:40 UTC
