### ISSUE TITLE
Android 12 bluetooth permission issue

### ISSUE THREAD

**Issue by arbaz8dots** [stripe/stripe-terminal-android#261] opened 2022-09-26 10:34 UTC
Terminal android sdk is not working in android 12 version, even if Bluetooth permission is granted runtime, please check below screen shot
![image](https://user-images.githubusercontent.com/114399091/192255503-6bb32bf0-d1f4-422a-81ed-71f9547672c3.png)

Below is screen shot of the exception getting from sdk 
![image](https://user-images.githubusercontent.com/114399091/192254666-cb551dbf-e089-4c31-936f-318eb4d33d6c.png)

Bluetooth permission issue with android 12 

 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                final int scanPermission = ActivityCompat.checkSelfPermission(getActivity(), Manifest.permission.BLUETOOTH_SCAN);
                final int connectPermission = ActivityCompat.checkSelfPermission(getActivity(), Manifest.permission.BLUETOOTH_CONNECT);
                if (locationPermission == PackageManager.PERMISSION_GRANTED && scanPermission == PackageManager.PERMISSION_GRANTED && connectPermission == PackageManager.PERMISSION_GRANTED) {
                    if (verifyGpsEnabled()) {
                        if (discoverymethod.equals("bluetooth")) {
                            showStripeBluetoothReaderDialog();
                        } else {
                            showStripInternetReaderDialog();
                        }

                    }
                } else {
                    // If we don't have them yet, request them before doing anything else
                    final String[] permissions = {Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.BLUETOOTH_CONNECT, Manifest.permission.BLUETOOTH_SCAN, Manifest.permission.BLUETOOTH_ADMIN};
                    requestPermissions(permissions, Constants.PERMISSION_CODE_LOCATION);
                }
            }

 if (isSimulated) {
                SimulatorConfiguration simulatorConfiguration = new SimulatorConfiguration(SimulateReaderUpdate.RANDOM, new SimulatedCard("4242424242424242"));
                Terminal.getInstance().setSimulatorConfiguration(simulatorConfiguration);
            }
            sendMessage("Discovering readers...", 0);
            DiscoveryConfiguration discoveryConfig = new DiscoveryConfiguration(0, DiscoveryMethod.BLUETOOTH_SCAN, isSimulated);
            cancelableDiscovery = Terminal.getInstance().discoverReaders(discoveryConfig, new DiscoveryListener() {
                @Override
                public void onUpdateDiscoveredReaders(@NonNull List<Reader> list) {
                    LogUtils.e("TERMINAL:::Discovery result::" + list.size());
                    getActivity().runOnUiThread(() -> {
                        ArrayList<Reader> readerArrayList = new ArrayList<>(list);
                        llLoaderView.setVisibility(View.GONE);
                        llReaderView.setVisibility(View.VISIBLE);
                        ArrayList<Object> localObjects = new ArrayList<>(list);
                        cardReaderAdapter.updateReaders(localObjects);
                    });
                }
            }, callback);

Android version 12

implementation "com.stripe:stripeterminal:2.13.1"

**Comment by billfinn-stripe** [comment] 2022-09-26 15:49
Hi @arbaz8dots -- can you reproduce the same problem using the example app provided in this repo running on the same device?

**Comment by arbaz8dots** [comment] 2022-09-30 07:41
> Hi @arbaz8dots -- can you reproduce the same problem using the example app provided in this repo running on the same device?

Yes able to reproduce the same problem using the example app provided in this repo

**Comment by billfinn-stripe** [comment] 2022-09-30 15:11
I am not able to reproduce using an Android 12 device (physical hardware). Please see screen recording:

![Screen Recording 2022-09-30 at 10 09 38 AM mov](https://user-images.githubusercontent.com/76448000/193300888-258264c7-1557-485d-b053-e7e167459264.gif)

If you are still experiencing this problem, can you reproduce using the example app and provide logcat output?

**Comment by rscherf** [comment] 2022-09-30 16:50
Possibly unrelated, but I'm also having some permission issues with older version of Android (Android 10, for example) and the way the example app requests permissions. I use most of the code from the example app, however this is the call that never fires on lower versions of Android:

https://github.com/stripe/stripe-terminal-android/blob/master/Example/javaapp/src/main/java/com/stripe/example/javaapp/MainActivity.java#L141

It's as if Android swallows the entire method, and no subsequent methods are called (and no permission screen displays), despite the app thinking `ACCESS_FINE_LOCATION` permission was denied.

**Comment by arbaz8dots** [comment] 2022-10-04 07:27
> I am not able to reproduce using an Android 12 device (physical hardware). Please see screen recording:
> 
> ![Screen Recording 2022-09-30 at 10 09 38 AM mov](https://user-images.githubusercontent.com/76448000/193300888-258264c7-1557-485d-b053-e7e167459264.gif) [ ![Screen Recording 2022-09-30 at 10 09 38 AM mov](https://user-images.githubusercontent.com/76448000/193300888-258264c7-1557-485d-b053-e7e167459264.gif) ](https://user-images.githubusercontent.com/76448000/193300888-258264c7-1557-485d-b053-e7e167459264.gif) [ ](https://user-images.githubusercontent.com/76448000/193300888-258264c7-1557-485d-b053-e7e167459264.gif)
> 
> If you are still experiencing this problem, can you reproduce using the example app and provide logcat output?

@billfinn-stripe Able to solve the issue, thank you for your quick response and support

**Comment by billfinn-stripe** [comment] 2022-10-04 14:38
@rscherf -- I'm going to close this issue. If you're still encountering a BT permission issue with older versions of Android, please open a new issue and fill out the issue template.

**Closed by billfinn-stripe** 2022-10-04 14:38 UTC
