### ISSUE TITLE
Terminal SDK stuck when connecting to turned-off reader

### ISSUE THREAD

**Issue by GhulJr** [stripe/stripe-terminal-android#313] opened 2023-04-28 13:12 UTC
Hello! c:

## Summary
`Terminal.getInstance().discoverReaders()` only update list when new reader appears and not when it disappears. Because of that, if user discovers reader, then will turn off it the one is still able to select it for connection. Unfortunately reader then stuck on connection for some time (around 3 minutes) before returning error. Disconnecting reader is also blocked. When reader is turned on again during that period, callbacks emits values as they should. In rare situations it can fail faster, but generally speaking it's unpredictable.
 
## Desired behaviour
Connection to turned off reader should fail asap and/or discovered readers list should also be updated when reader disappears.

## Code to reproduce
1. Run `Terminal.getInstance().discoverReaders()`
2. List is updated with discovered readers in `onUpdateDiscoveredReaders(readers: List<Reader>)`
3. Turn off discovered reader
4. `onUpdateDiscoveredReaders(readers: List<Reader>)` does not update such change
5. Try to connect to this reader with `Terminal.getInstance().connectBluetoothReader()`
6. Will take few minutes to receive any event in `ReaderCallback` with no way to cancel it.

## Android version
Google Pixel 5 API 33

## Impacted devices (Android devices or readers)
BBPOS WisePad 3 and Stripe Reader M2

## SDK version
Stripe SDK - 2.19.0

If something is unclear just let me know :)

**Comment by chr-stripe** [comment] 2023-06-26 19:13
This issue seems to be really about two separate, but related, issues:

1. Once a reader has been discovered, it never disappears from the scan list
2. Connecting to a reader that is off never returns anything

The first one will be resolved in the upcoming `2.22.0` SDK release. We are targeting to release this SDK next week.

The second issue is not resolved yet, but it is being tracked internally and we will plan this for a future release.

**Comment by federicopolesello** [comment] 2023-09-06 15:35
I noticed the same issue as well. I'm stucked with this because the app is not ready for the production due to these stability issue.
Could you try to replicate the issue and provide us an ETA to fix this issue?
The issue still persists in the SDK version `2.23.1` (the latest one).
Thank you very much

**Comment by ugochukwu-stripe** [comment] 2024-03-08 17:06
Closing, since I can't reproduce with the latest version, could you please upgrade to the latest version of the Stripe Terminal Android SDK. Many issues like this one are often resolved in new releases with bug fixes and enhancements. Please feel free to open a new issue with all steps to reproduce if you're still facing the same problem after an upgrade. Thanks

**Closed by ugochukwu-stripe** 2024-03-08 17:06 UTC
