### ISSUE TITLE
E/StripeTerminal: READER_ERROR.BLUETOOTH_ERROR: BLE initialization no responsed

### ISSUE THREAD

**Issue by anton8900** [stripe/stripe-terminal-android#86] opened 2019-12-24 13:25 UTC
Received this error when trying to connect reader

12-24 16:23:06.128 26686-27375/au.com.ticketbooth.rfid.android E/StripeTerminal: READER_ERROR.BLUETOOTH_ERROR: BLE initialization no responsed
    com.stripe.stripeterminal.model.external.TerminalException
        at com.stripe.stripeterminal.bbpos.BbposDeviceControllerListener.fail(BbposDeviceControllerListener.kt:757)
        at com.stripe.stripeterminal.bbpos.BbposDeviceControllerListener.onError(BbposDeviceControllerListener.kt:598)
        at com.stripe.bbpos.bbdevice.BBDeviceController$aaa007zz.run(SourceFile:1)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5738)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
12-24 16:23:06.141 15494-15513/? E/BluetoothRemoteDevices: state12newState1
12-24 16:23:06.143 26686-26686/au.com.ticketbooth.rfid.android E/TokenLogService: null
    com.stripe.stripeterminal.model.external.TerminalException
        at com.stripe.stripeterminal.bbpos.BbposDeviceControllerListener.fail(BbposDeviceControllerListener.kt:757)
        at com.stripe.stripeterminal.bbpos.BbposDeviceControllerListener.onError(BbposDeviceControllerListener.kt:598)
        at com.stripe.bbpos.bbdevice.BBDeviceController$aaa007zz.run(SourceFile:1)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5738)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
12-24 16:23:06.144 26686-26686/au.com.ticketbooth.rfid.android E/TokenLogService: null
    com.stripe.stripeterminal.model.external.TerminalException
        at com.stripe.stripeterminal.bbpos.BbposDeviceControllerListener.fail(BbposDeviceControllerListener.kt:757)
        at com.stripe.stripeterminal.bbpos.BbposDeviceControllerListener.onError(BbposDeviceControllerListener.kt:598)
        at com.stripe.bbpos.bbdevice.BBDeviceController$aaa007zz.run(SourceFile:1)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5738)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
12-24 16:23:06.145 26686-26686/au.com.ticketbooth.rfid.android E/TokenLogService: null
    com.stripe.stripeterminal.model.external.TerminalException
        at com.stripe.stripeterminal.bbpos.BbposDeviceControllerListener.fail(BbposDeviceControllerListener.kt:757)
        at com.stripe.stripeterminal.bbpos.BbposDeviceControllerListener.onError(BbposDeviceControllerListener.kt:598)
        at com.stripe.bbpos.bbdevice.BBDeviceController$aaa007zz.run(SourceFile:1)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5738)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)

**Comment by anton8900** [comment] 2019-12-24 13:31
after several more tries to connect it started to work, helped only rebooting the terminal, rebooting the app didn't work

**Comment by legomanaustralia** [comment] 2020-01-01 22:39
Turns out this start recurring again and we had to fall back to the older b7 library, it appears as though the BLE implementation doesn't seem stable on some older android v6 devices.

**Comment by Jarrette** [comment] 2020-01-31 16:51
I can verify that I'm experiencing this as well but on Android 9 terminal version 1.0.2.  Beta 9 works fine.  Discovery works sometimes, sometimes it hangs until crash.

**Comment by Jarrette** [comment] 2020-02-03 18:58
so far as I can tell stripeterminal:1.0.8 is connecting 100% of the time.  I'm going to continue testing but it appears as the issue might have been fixed.

**Comment by Jarrette** [comment] 2020-02-04 17:20
never mind, it's happening on a different tablet and reader.  Works fine in older version, just can't connect in newer version randomly.  Android version 9 terminal version 1.0.8

2020-02-04 11:16:21.987 29905-30205/tenfore.birdie E/StripeTerminal: NETWORK_ERROR.REQUEST_TIMED_OUT: Stripe API request timed out.
    com.stripe.stripeterminal.model.external.TerminalException
        at com.stripe.stripeterminal.api.ApiClient.sendRequest(ApiClient.kt:119)
        at com.stripe.stripeterminal.api.ApiClient.generatePosSdkSession(ApiClient.kt:65)
        at com.stripe.stripeterminal.TerminalSession$ConnectReaderOperation.run$stripeterminal_release(TerminalSession.kt:500)
        at com.stripe.stripeterminal.TerminalSession$enqueueOperation$1.run(TerminalSession.kt:208)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

2020-02-04 11:17:02.607 29905-29905/tenfore.birdie E/AndroidRuntime: FATAL EXCEPTION: main
    Process: tenfore.birdie, PID: 29905
    io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.stripe.stripeterminal.model.external.ConnectionTokenException: Creating connection token failed
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:126)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7156)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
     Caused by: com.stripe.stripeterminal.model.external.ConnectionTokenException: Creating connection token failed
        at tenfore.birdie.utils.terminal.TokenProvider$fetchConnectionToken$1.onError(TokenProvider.kt:70)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7156) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975) 
     Caused by: java.net.SocketTimeoutException: SSL handshake timed out
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:383)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:351)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:310)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:178)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:215)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
2020-02-04 11:17:02.608 29905-29905/tenfore.birdie E/AndroidRuntime:     at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by Jarrette** [comment] 2020-02-04 18:12
I did a software update on the second tablet and now everything works fine.  Samsung galaxy tab A 10.5.

**Comment by chander-stripe** [comment] 2020-07-07 18:38
Just tested on my Samsung A51 and it seems to work as well. Might this just be an older Samsung OS issue?

(Tried on SDK [version 1.0.17](https://mvnrepository.com/artifact/com.stripe/stripeterminal/1.0.17))

**Comment by chander-stripe** [comment] 2020-07-07 18:49
@Jarrette if you're still running into this, feel free to re-open! Going to close it for now based on your Feb 4th reply.

**Closed by chander-stripe** 2020-07-07 18:49 UTC
