### ISSUE TITLE
Discover card in Apple pay failed to collectPaymentMethod , but sent a text message to the user

### ISSUE THREAD

**Issue by chance-yang** [stripe/stripe-terminal-android#371] opened 2023-09-14 05:07 UTC
## Summary

Discover card in Apple pay failed to collectPaymentMethod , but sent a text message to the user. 
Logs：
<img width="1252" alt="image" src="https://github.com/stripe/stripe-terminal-android/assets/25995306/6346e015-6034-49f3-8fb6-d8846fc47c46">

## Android version

Android 9

## Impacted devices (Android devices or readers)

Sunmi T2s
Stripe Reader M2

## SDK version

com.stripe:stripeterminal:3.0.0-b1
com.stripe:stripeterminal-localmobile:2.22.0
com.stripe:stripeterminal-core:2.22.0

## Other information

Card Reader connect with USB
M2 SN : STRM26229025861
Firmware versions : 2.01.00.17-SZZZ_Prod_US_v5-480001

**Comment by bric-stripe** [comment] 2023-09-14 20:47
Hi, Discover card via Apple Pay failing is an ongoing issue. https://github.com/stripe/stripe-terminal-android/issues/316 is the open issue for that.

Regarding the text message being sent, can you provide any more details on that? Was it an authentication challenge? Since the collectPaymentMethod wasn't successfully reading the Apple Pay card there shouldn't have been anything charged or even auth'd on the card. I confirmed with the PaymentIntent from the screenshot the only card brand seen for that was a visa (which I assume is what it was changed to).

**Comment by chance-yang** [comment] 2023-09-18 05:21
Hi @bric-stripe , thanks for your reply.I just heard from customers that they received text messages. No more detailed information

**Comment by chance-yang** [comment] 2023-09-18 05:21
Hi @bric-stripe , thanks for your reply.I just heard from customers that they received text messages. No more detailed information

**Comment by bric-stripe** [comment] 2023-09-18 16:31
OK, let us know if you get more info on the text messages but since the reader didn't successfully read the card it shouldn't have been from that. I'm going to close this issue though, please follow #316 for updates on the discover card fix (still being worked on).

**Closed by bric-stripe** 2023-09-18 16:31 UTC
