### ISSUE TITLE
[URGENT] Stripe terminal SDK doesn't return callback for createPaymentIntent() and processPayment()

### ISSUE THREAD

**Issue by coolbeet** [stripe/stripe-terminal-android#212] opened 2022-03-17 21:47 UTC
We have been using chipper USB connectivity for a while now. Though connectivity is very stable, there is one issue that keeps happening and need to be fixed right now:

When the app successfully collect the payment method and call processPayment() to process the payment, the app never got a callback from the SDK, after 60s we have to timeout and cancel this payment and send the customer back to the checkout page to recreate a new payment intent, but after the app calls createPaymentIntent() it will again not get a callback from the SDK and then timeout. From this point, the SDK can't make any payment since it can't create any payment intent.

Also, sometimes createPaymentIntent() just doesn't get any callback even before we call processPayment()

This seems to me that at this point the SDK can't make any API call to the stripe server, I checked the log it seems like Stripe didn't receive any call from the above requests without a callback, pretty much we are stuck here.

Also, sometimes we did see that onRequestReaderDisplayMessage() returns "Check Your Mobile Device" and the above issue happens.

<img width="939" alt="CleanShot 2022-03-17 at 16 46 15@2x" src="https://user-images.githubusercontent.com/2062490/158900138-804a9159-b726-4e9a-bd93-3c7c8ad41c55.png">

The only way to fix this is restarting the app which essentially restarts the Stripe SDK.

While you guys figure this out, is there any way to restart the Stripe SDK without restarting the entire app?

Some details for you guys to debug:
SDK: android 2.7
Reader series number: CHB202009000506
Reader firmware version: should be the latest
IP: 173.68.94.234  (note that we have multiple devices from this IP)

**Comment by dhenry-stripe** [comment] 2022-03-18 01:55
Hi @coolbeet, thanks for the detailed report. Please confirm a few things to help with our investigation:

Is this a duplicate of this issue reported earlier? https://github.com/stripe/stripe-terminal-android/issues/210
Can you reliably reproduce the issue? If so, is it reproducible using the Stripe example app?
Do you have customers that use Bluetooth connectivity? If so, have those users experienced the issue? 

> While you guys figure this out, is there any way to restart the Stripe SDK without restarting the entire app?

The SDK doesn't have anything built in to do this. One potential workaround is to have the app restart itself programmatically, eg: https://stackoverflow.com/a/46848226/5482166

> When the app successfully collect the payment method and call processPayment() to process the payment, the app never got a callback from the SDK

The logs on our side show no evidence of processPayment being called - I'm not saying it didn't happen, I just don't see a record of it occurring. This suggests one of a number of things: sudden network loss that stopped the SDK from sending logs, a concurrency issue caused the SDK to lock up, the app crashed, or something in the app stopped working prior to processPayment being called. Can you please confirm that processPayment is definitely getting called, and if you can please reproduce the issue and send through the resulting device logs.

**Comment by coolbeet** [comment] 2022-03-18 02:05
> Is this a duplicate of this issue reported earlier? https://github.com/stripe/stripe-terminal-android/issues/210

Yes this is the same issue with #210 with more details.

> Can you reliably reproduce the issue? If so, is it reproducible using the Stripe example app?

No, this happened randomly and mostly to a restaurant that has a high number of transactions.

> Do you have customers that use Bluetooth connectivity? If so, have those users experienced the issue?

I haven't experienced this happened for Bluetooth, only USB

> The logs on our side show no evidence of processPayment being called - I'm not saying it didn't happen, I just don't see a record of it occurring. This suggests one of a number of things: sudden network loss that stopped the SDK from sending logs, a concurrency issue caused the SDK to lock up, the app crashed, or something in the app stopped working prior to processPayment being called. Can you please confirm that processPayment is definitely getting called, and if you can please reproduce the issue and send through the resulting device logs.

We are pretty sure about both createPaymentIntent() and processPayment() got called, and we are also believe that the network was pretty stable because they used wired solution not wifi, also we are seeing the same thing on dashboard.stripe.com/logs and no web request has been sent out.

It seems like the web request didn't get out for some reason, maybe an error thrown out by the SDK we didn't catch?

Thanks

**Comment by dhenry-stripe** [comment] 2022-03-18 02:11
Thanks @coolbeet, that's helpful. 

> I haven't experienced this happened for Bluetooth, only USB

Can you have the affected user switch to Bluetooth to see if this resolves the problem? We don't yet know whether this is connection type or SDK version specific.

> It seems like the web request didn't get out for some reason, maybe an error thrown out by the SDK we didn't catch?

Sure, this is possible. Do you have access to the affected devices? Can you retrieve the logs for when the error occurs?

**Comment by coolbeet** [comment] 2022-03-18 02:13
> Can you have the affected user switch to Bluetooth to see if this resolves the problem? We don't yet know whether this is connection type or SDK version specific.

Actually we were using Bluetooth but it got disconnected unexpectedly too often, so we switched to USB.

> Sure, this is possible. Do you have access to the affected devices? Can you retrieve the logs for when the error occurs?

No we don't have access to the log

**Closed** 2022-03-23 16:43 UTC

**Comment by rv-stripe** [comment] 2022-03-23 16:52
@coolbeet This issue should be resolved in 2.7.1
Thank you again for the detailed report and making us aware of the issue!
