### ISSUE TITLE
reader hangs at "remove card"

### ISSUE THREAD

**Issue by Jarrette** [stripe/stripe-terminal-android#68] opened 2019-09-18 23:35 UTC
I just had a launch with stripe terminal on android and everything is working mostly, but every once in a while, when the status reads "remove card", and the card is removed, nothing happens.  It never gets to "Collected Payment", I know this is not a lot of info, just now starting to look into it to see what is happening.
I checked the payments in the stripe portal, and there is a paymentIntent that is created, but never completed.  The payment in the portal says "Payment started" with a status of "incomplete"
This happens randomly as most credit cards work with no issue.

Just looking for ideas on where to start.

**Comment by chander-stripe** [comment] 2019-09-18 23:39
Hi @Jarrette , thanks for reaching out - couple follow up questions for you
a) what version of the SDK are you using
b) what version of Android Studio / general Android setup (androidx ?  support lib? etc)
c) can you set your logging to verbose and send me the logs if you ever notice this happen again?

**Comment by Jarrette** [comment] 2019-09-18 23:40
a -     implementation "com.stripe:stripeterminal:1.0.0-rc1"

**Comment by Jarrette** [comment] 2019-09-18 23:52
the other part of this is that the app has to be completely shut down and reopened when this happens, it's like the status won't update anymore unless you start from scratch.  Is there a method I can call that will "reset" the flow?

**Comment by chander-stripe** [comment] 2019-09-19 00:03
hmm we don't really have a 'reset' issue because we don't expect this sort of thing to ever happen haha. let me take a look at this particular payment intent and see if i can see anything weird going on.

**Comment by Jarrette** [comment] 2019-09-19 00:10
ok, something strange I just noticed neither onSucess not onFailure are getting hit on processPaymentCallback when I tried a certain bad card.  

`    private val collectPaymentMethodCallback by lazy {
        object : PaymentIntentCallback {
            override fun onSuccess(paymentIntent: PaymentIntent) {
                LogUtil.log("webs: collectPaymentMethodCallback.success")
                displayCardReaderEvent("Collected Payment", "terminal.collectPaymentMethod")
                Terminal.getInstance().processPayment(paymentIntent, processPaymentCallback)
                collectCancelable = null
            }

            override fun onFailure(e: TerminalException) {
                LogUtil.log("webs: collectPaymentMethodCallback.fail : " + e.errorMessage)
                displayCardReaderEvent("Payment Failed", e.errorMessage)
                handleFail(e, "Collect Payment Failed")
            }
        }
    }

    private val processPaymentCallback by lazy {
        object : PaymentIntentCallback {
            override fun onSuccess(paymentIntent: PaymentIntent) {
                LogUtil.log("webs: processPaymentCallback.success")
                when {

                    activityProShopPayment4 != null -> {
                        activityProShopPayment4!!.paymentIntentID = paymentIntent.id
                        runOnUiThread {
                            activityProShopPayment4!!.runCreditCardPayment()
                        }
                    }
                    activityRestaurantQuickPayment4 != null -> {
                        activityRestaurantQuickPayment4!!.paymentIntentID = paymentIntent.id
                        runOnUiThread {
                            activityRestaurantQuickPayment4!!.runCreditCardPayment()
                        }
                    }

                }
            }

            override fun onFailure(e: TerminalException) {
                LogUtil.log("webs stripe processPaymentCallback.fail: " + e.message)
                handleFail(e, "Process Payment Failed")
            }
        }
    }`


so in my logs, with just certain cards, i only get collectPaymentMethodCallback.success, but never  processPaymentCallback.success or  processPaymentCallback.fail.  On successful tries I do.

**Comment by Jarrette** [comment] 2019-09-19 00:28
here is the flow:

https://gist.github.com/Jarrette/e4d086956f7eacf4be2de3a38843758d

**Comment by Jarrette** [comment] 2019-09-19 01:18
ok, i reverted back to 1.0.0-b9 and I'm not getting this issue anymore.  Guess it's a bug in the new version, unless I'm missing something.

**Comment by danwaters-stripe** [comment] 2019-09-19 01:39
Hmm. We're glad you were able to get things working again, but we'd love to figure out what's going wrong when you have some extra time. Can you send us the logs of a failure whenever you're able to? Thanks!

**Comment by Jarrette** [comment] 2019-09-19 12:57
That's the thing, it wouldn't fail so there were no logs.  onFailure would never fire inside processPaymentCallback in these instances.  So the app would just sit in limbo.

**Comment by Jarrette** [comment] 2020-01-08 16:03
@danwaters-stripe any updates on this?  Just came back to non-beta (1.0.1) because I know the deadline is approaching.  Now I'm getting this issue randomly.  The whole library also seems slower than beta.

**Comment by Jarrette** [comment] 2020-01-08 16:45
here are my custom logs:

2020-01-08 10:33:47.979 29959-30125/tenfore.birdie D/ActivityTerminal$createPaymentIntentCallback$2$1.onSuccess():188: tfstripe createPaymentIntentCallback.success
2020-01-08 10:34:01.075 29959-30125/tenfore.birdie D/ActivityTerminal$collectPaymentMethodCallback$2$1.onSuccess():202: tfstripe collectPaymentMethodCallback.success
2020-01-08 10:34:02.431 29959-30125/tenfore.birdie D/ActivityTerminal$processPaymentCallback$2$1.onSuccess():219: tfstripe processPaymentCallback.success
2020-01-08 10:35:24.216 29959-30125/tenfore.birdie D/ActivityTerminal$createPaymentIntentCallback$2$1.onSuccess():188: tfstripe createPaymentIntentCallback.success
2020-01-08 10:35:37.791 29959-30125/tenfore.birdie D/ActivityTerminal$collectPaymentMethodCallback$2$1.onSuccess():202: tfstripe collectPaymentMethodCallback.success
2020-01-08 10:35:39.195 29959-30125/tenfore.birdie D/ActivityTerminal$processPaymentCallback$2$1.onSuccess():219: tfstripe processPaymentCallback.success
2020-01-08 10:39:23.606 29959-30125/tenfore.birdie D/ActivityTerminal$createPaymentIntentCallback$2$1.onSuccess():188: tfstripe createPaymentIntentCallback.success
2020-01-08 10:39:37.586 29959-30125/tenfore.birdie D/ActivityTerminal$collectPaymentMethodCallback$2$1.onSuccess():202: tfstripe collectPaymentMethodCallback.success
2020-01-08 10:39:39.117 29959-30125/tenfore.birdie D/ActivityTerminal$processPaymentCallback$2$1.onSuccess():219: tfstripe processPaymentCallback.success
2020-01-08 10:42:26.225 29959-30125/tenfore.birdie D/ActivityTerminal$createPaymentIntentCallback$2$1.onSuccess():188: tfstripe createPaymentIntentCallback.success

As you can see the first 3 attempts worked fine, but a little slow.  About 15 seconds from authorize button pressed to completed order.  The fourth attempt just hung, createPaymentIntentCallback was successfull, but collectPaymentMethodCallback was never fired....

**Comment by Jarrette** [comment] 2020-01-08 16:50
Here is the relevant code snippet:

`    override fun onRequestPayment(amount: Int, currency: String) {
        val params = PaymentIntentParameters.Builder()
                .setAmount(amount)
                .setCurrency(currency.toLowerCase())
                .setStatementDescriptor(app.selectedGolfCourse!!.golfCourseName!!.take(15))
                .build()
        Terminal.getInstance().createPaymentIntent(params, createPaymentIntentCallback)
    }

    private val createPaymentIntentCallback by lazy {
        object : PaymentIntentCallback {
            override fun onSuccess(paymentIntent: PaymentIntent) {
                LogUtil.log("tfstripe createPaymentIntentCallback.success")
                collectCancelable = Terminal.getInstance().collectPaymentMethod(paymentIntent, this@ActivityTerminal, collectPaymentMethodCallback)
            }

            override fun onFailure(e: TerminalException) {
                LogUtil.log("tfstripe Payment Intent Create Failed : " + e.errorMessage)
                handleFail(e, "Payment Intent Create Failed")
            }
        }
    }

    private val collectPaymentMethodCallback by lazy {
        object : PaymentIntentCallback {
            override fun onSuccess(paymentIntent: PaymentIntent) {
                LogUtil.log("tfstripe collectPaymentMethodCallback.success")
                displayCardReaderEvent("Collected Payment", "terminal.collectPaymentMethod")
                Terminal.getInstance().processPayment(paymentIntent, processPaymentCallback)
                collectCancelable = null
            }

            override fun onFailure(e: TerminalException) {
                LogUtil.log("tfstripe collectPaymentMethodCallback.fail : " + e.errorMessage)
                displayCardReaderEvent("Payment Failed", e.errorMessage)
                handleFail(e, "Collect Payment Failed")
            }
        }
    }`

**Comment by chander-stripe** [comment] 2020-01-08 18:03
@Jarrette this mostly looks right to me. Does our example app hang for you as well?
When you say the library is slower, which specific APIs are slower for you?

**Comment by Jarrette** [comment] 2020-01-08 18:16
to get through all 3 of the above methods, 1.0.1 takes 15 seconds, 1.0.0-b9 takes 3-4 seconds.  It's a LOT slower, not really sure why.  

I can't get the sample app to run on my devices.  I'm not sure if I imported it correctly, but I just get "Add Configuration..." button instead of "app" on my AS toolbar.  Is there a detailed setup for the sample app to get it to run the kotlin app on a device?

**Comment by chander-stripe** [comment] 2020-01-08 18:20
Hmmm something's wrong there then. You should be able to just clone the repo and get the example apps available immediately.

**Comment by chander-stripe** [comment] 2020-01-08 18:21
Can you click through add configuration and add the kotlinapp as a module to configure?

**Comment by Jarrette** [comment] 2020-01-08 18:22
Message from Gopher Angels:

Thanks for applying to Gopher Angels. After reviewing your information, we have decided to pass on this opportunity. Gopher Angels invest in Minnesota (USA) businesses only unless referred by another angel group taking the lead. We wish you the best of luck.

**Comment by Jarrette** [comment] 2020-01-08 18:27
I'll work on getting the sample up running on IDE and update this comment when I'm able to test it.

**Comment by Jarrette** [comment] 2020-01-08 18:33
@chander-stripe ok, i cloned the project as a zip file, unzipped to windows 10 directory, went to file-> open in AS, navigated to Example App, get this error immediately:

ERROR: Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/5.6.1/userguide/gradle_daemon.html
Process command line: C:\Program Files (x86)\Java\jdk1.8.0_172\bin\java.exe -Xmx1536m -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\tonyq\.gradle\wrapper\dists\gradle-5.6.1-all\805usxkvhgx6e1wbo8o64g0tx\gradle-5.6.1\lib\gradle-launcher-5.6.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 5.6.1
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 1572864KB object heap

**Comment by chander-stripe** [comment] 2020-01-08 18:36
@Jarrette yeah that can happen sometimes - can you follow the steps [here](https://stackoverflow.com/questions/30045417/android-gradle-could-not-reserve-enough-space-for-object-heap) and let me know if that solves it?

**Comment by Jarrette** [comment] 2020-01-08 19:00
@chander-stripe ok, got sample app running and it's not slow at all, very responsive.  Not really sure what the issue is on my end.  Back to the drawing board...

**Comment by chander-stripe** [comment] 2020-01-08 19:23
Awesome, glad to hear. I'd recommend modeling your app based on the example apps as much as possible, and hopefully that'll help to highlight the issue.

**Comment by Jarrette** [comment] 2020-02-10 16:19
@chander-stripe ok, back to the original subject of this issue. I'm still having this issue with newer versions of the stripe library.  Currently testing with 1.0.8.

Here are the logs from the listeners:
```

2020-02-10 10:11:54.028 10982-11139/tenfore.birdie D/StripeTerminal: ActivityTerminal$createPaymentIntentCallback$2$1.onSuccess():212 - tfstripe createPaymentIntentCallback.success
2020-02-10 10:12:07.483 10982-11139/tenfore.birdie D/StripeTerminal: ActivityTerminal$collectPaymentMethodCallback$2$1.onSuccess():229 - tfstripe collectPaymentMethodCallback.success
2020-02-10 10:12:09.149 10982-11139/tenfore.birdie D/StripeTerminal: ActivityTerminal$processPaymentCallback$2$1.onSuccess():247 - tfstripe processPaymentCallback.success
2020-02-10 10:12:20.550 10982-10982/tenfore.birdie D/StripeTerminal: ActivityTerminal.onRequestPayment():196 - tfstripe onRequestPayment
2020-02-10 10:12:20.888 10982-11139/tenfore.birdie D/StripeTerminal: ActivityTerminal$createPaymentIntentCallback$2$1.onSuccess():212 - tfstripe createPaymentIntentCallback.success
2020-02-10 10:12:34.822 10982-11139/tenfore.birdie D/StripeTerminal: ActivityTerminal$collectPaymentMethodCallback$2$1.onSuccess():229 - tfstripe collectPaymentMethodCallback.success
2020-02-10 10:12:36.291 10982-11139/tenfore.birdie D/StripeTerminal: ActivityTerminal$processPaymentCallback$2$1.onSuccess():247 - tfstripe processPaymentCallback.success
2020-02-10 10:12:48.671 10982-10982/tenfore.birdie D/StripeTerminal: ActivityTerminal.onRequestPayment():196 - tfstripe onRequestPayment
2020-02-10 10:12:49.183 10982-11139/tenfore.birdie D/StripeTerminal: ActivityTerminal$createPaymentIntentCallback$2$1.onSuccess():212 - tfstripe createPaymentIntentCallback.success

```
What you see is 2 normal transactions that worked, then the last one that just hung at "remove card", so createPaymentIntentCallback hit onSuccess, but collectPaymentMethodCallback is never fired, neither success nor fail.  It just sits there.  This only happens RANDOMLY and NEVER happens in beta versions of the stripe terminal library.  

How can I diagnose this if no failure is triggered?  How can I move forward?

Something get's lost between these 2 methods:

```
    private val createPaymentIntentCallback by lazy {
        object : PaymentIntentCallback {
            override fun onSuccess(intent: PaymentIntent) {
                LogUtil.log("tfstripe createPaymentIntentCallback.success")

                paymentIntent = intent
                viewModel.collectTask = Terminal.getInstance().collectPaymentMethod(
                        intent, this@ActivityTerminal, collectPaymentMethodCallback)
            }

            override fun onFailure(e: TerminalException) {
                LogUtil.log("tfstripe Payment Intent Create Failed : " + e.errorMessage)
                handleFail(e, "Payment Intent Create Failed")
            }
        }
    }

    private val collectPaymentMethodCallback by lazy {
        object : PaymentIntentCallback {
            override fun onSuccess(paymentIntent: PaymentIntent) {
                LogUtil.log("tfstripe collectPaymentMethodCallback.success")
                displayCardReaderEvent("Collected Payment", "terminal.collectPaymentMethod")
                Terminal.getInstance().processPayment(paymentIntent, processPaymentCallback)
                viewModel.collectTask = null
            }

            override fun onFailure(e: TerminalException) {
                LogUtil.log("tfstripe collectPaymentMethodCallback.fail : " + e.errorMessage)

                displayCardReaderEvent("Payment Failed", e.errorMessage)
                handleFail(e, "Collect Payment Failed")
            }


        }
    }
```

**Comment by Jarrette** [comment] 2020-02-17 17:08
@chander-stripe @danwaters-stripe  is this being looked at?  Are there any listeners I can add that would catch a time out like this?

**Comment by chander-stripe** [comment] 2020-03-07 00:46
@Jarrette can we reroute this to the Stripe technical support staff instead? Since it works on the example app, I'm fairly convinced it's not a bug with the SDK. The technical support team can help investigate in a deeper manner that's more specific to your particular set up. Closing this out for now, as we use github issues to diagnose whether there's a bug on the SDK. Thanks!

**Closed by chander-stripe** 2020-03-07 00:46 UTC
