### ISSUE TITLE
UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR

### ISSUE THREAD

**Issue by RobertoPerezCK** [stripe/stripe-terminal-android#361] opened 2023-08-04 23:59 UTC
## Summary
When trying to connect to the local NFC card reader for Tap to Pay in release/production mode (isSimulated = false), the SDK throws:

08-04 16:54:03.349 22979 26396 I StripeTerminal: class=RestClient message="url=https://api.stripe.com/v1/terminal/locations/...
08-04 16:54:03.352 22979 26396 I StripeTerminal: class=TerminalSession reader_id=tmr_FMpTFQOdY6xqvD account_id=acct_1MrpbdCaMYXjxkZL
08-04 16:54:03.352 22979 26396 I StripeTerminal: class=TerminalStatusManager message=connected.
08-04 16:54:04.270 22979 26396 I StripeTerminal: class=CotsAdapter message=disconnectReader
08-04 16:54:04.279 22979 26396 I StripeTerminal: class=TerminalStatusManager message=notConnected.
08-04 16:54:04.280 22979 26396 E StripeTerminal: class=TerminalSession
08-04 16:54:04.280 22979 26396 E StripeTerminal: com.stripe.stripeterminal.external.models.TerminalException: Unexpected error occurred
08-04 16:54:04.280 22979 26396 E StripeTerminal: 	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.checkAndThrowCotsError(SourceFile:82)
08-04 16:54:04.280 22979 26396 E StripeTerminal: 	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.onReaderActivated(SourceFile:60)
08-04 16:54:04.280 22979 26396 E StripeTerminal: 	at com.stripe.stripeterminal.internal.common.adapter.ProxyAdapter.onReaderActivated(SourceFile:10)
08-04 16:54:04.280 22979 26396 E StripeTerminal: 	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ConnectReaderOperation.execute(SourceFile:277)
08-04 16:54:04.280 22979 26396 E StripeTerminal: 	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ExternalOperation.run$terminalsession_release(SourceFile:17)
08-04 16:54:04.280 22979 26396 E StripeTerminal: 	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda$6(SourceFile:52)
08-04 16:54:04.280 22979 26396 E StripeTerminal: 	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.a(SourceFile:1)
08-04 16:54:04.280 22979 26396 E StripeTerminal: 	at es.m.run(SourceFile:86)
08-04 16:54:04.280 22979 26396 E StripeTerminal: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
08-04 16:54:04.280 22979 26396 E StripeTerminal: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
08-04 16:54:04.280 22979 26396 E StripeTerminal: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
08-04 16:54:04.280 22979 26396 E StripeTerminal: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
08-04 16:54:04.280 22979 26396 E StripeTerminal: 	at java.lang.Thread.run(Thread.java:1012)

Notes:
- This error is not reported if the application is compiled in debug mode and the DiscoveryConfiguration#isSimulated is set to "true".
- The same device (phone) can pair with BT card readers without a problem in both debug and release modes.

## Code to reproduce
val config = DiscoveryConfiguration(
  0,
  DiscoveryMethod.LOCAL_MOBILE),
  false)

Terminal.getInstance().discoverReaders(
  config,
  object : DiscoveryListener {
    override fun onUpdateDiscoveredReaders(readers: List<Reader>) {
       ...
    }
  },
  object : Callback {
    override fun onFailure(e: TerminalException) {
       ...
    }
    override fun onSuccess() {
       ...
    }
  })

## Android version
Android 13

## Impacted devices (Android devices or readers)
Pixel 6 Pro

## SDK version
com.stripe:stripe-android:20.27.3
com.stripe:stripeterminal-core:2.21.1
com.stripe:stripeterminal-handoffclient:2.21.1
com.stripe:stripeterminal-localmobile:2.21.1

## Other information
Please let me know if there is any way to gather more information on the exact cause of the exception (I couldn't get anything else from the logs).

**Comment by maggiewhite-stripe** [comment] 2023-08-24 00:10
Hi @RobertoPerezCK, I pulled up our backend logs and they have about the same amount of information shared in your report. The discoverReader call succeeds, and the connectReader call fails after ~3 seconds.

From our logs, it looks like this specific error has occurred 4 times in the last month on your accounts' devices. I see instances of this error on SDK version 2.23.0, so it is not resolved on a newer version of the SDK.

Do you have any other information about the behavior observed, for example:
- Is this easy to reproduce? If so, how do you reproduce this issue?
- How often are you seeing this issue?
- Does connectReader work if you retry the method call?

**Comment by maggiewhite-stripe** [comment] 2023-08-24 01:25
I do see from a couple of the instances of this issue that discoverReaders is called three times before connectLocalMobileReader is invoked.

On the:
-  discoverReaders call with LOCAL_MOBILE at Wed Aug 02 2023 20:39:59 the operation is canceled after 1.3 seconds.
- discoverReaders call with bluetooth at Wed Aug 02 2023 20:40:00 is canceled after 4 seconds
- discoverReaders call with LOCAL_MOBILE at Wed Aug 02 2023 20:40:04 succeeds after 300 ms
- connectReaders call with LOCAL_MOBILE at Wed Aug 02 2023 20:40:04 fails due to "com.stripe.stripeterminal.external.models.TerminalException: Unexpected error occurred"
- connectReaders call with LOCAL_MOBILE at Wed Aug 02 2023 20:40:19 failed due to "com.stripe.stripeterminal.external.models.TerminalException: com.google.firebase.perf.config.RemoteConfigManager"
- 4th discoverReaders call with LOCAL_MOBILE at Wed Aug 02 2023 20:40:19 succeeds after 500ms
- 5th discoverReaders call with LOCAL_MOBILE at Wed Aug 02 2023 20:41:20 is canceled after 600ms
- 6th discoverReaders call with bluetooth at Wed Aug 02 2023 20:41:20 is canceled after 2.2 seconds
- 7th discoverReaders call with bluetooth at Wed Aug 02 2023 20:41:22 is succeeds after 1 second
- connectReader call with bluetooth succeeds at Wed Aug 02 2023 20:41:23

In other instances of this error, there is a similar profile of canceling discoverReaders calls one or multiple times in a very short time span before calling connectReader. It looks like all of these errors occurred on a Pixel 6 Pro, which I would guess is an internal development device. My initial instinct is that something strange is happening when discoverReaders is cancelled very shortly after it is invoked, and my recommendation would be to not implement your integration in a way that causes that to happen (if possible)

**Comment by chr-stripe** [comment] 2023-11-10 01:44
Hi @RobertoPerezCK, I believe what you might be running into is a duplicate of #323. Can you attempt the workaround mentioned in [this comment on that issue](https://github.com/stripe/stripe-terminal-android/issues/323#issuecomment-1804944177) and verify that solves your Tap to Pay connection issue?

**Comment by chr-stripe** [comment] 2023-11-28 23:39
Closing due to inactivity. Feel free to let us know if the resolution in that linked ticket does not fix this for you!

**Closed by chr-stripe** 2023-11-28 23:39 UTC
Labels: Tap to Pay
