### ISSUE TITLE
Receive onUnexpectedReaderDisconnect event at the same time  everyday  , everyday ,  everyday

### ISSUE THREAD

**Issue by Mike-Android-Chow** [stripe/stripe-terminal-android#292] opened 2023-02-23 07:28 UTC
We use the usb to connect the reader, but we receive the  **onUnexpectedReaderDisconnect** event at the same time _everyday_ , please help to check it why this happen.

Android Version : 7.1.2
Terminal SDK Version: 2.14.0
Reader SerialNumber: STRM26146045306
Reader FirmwareVersion: 2.01.00.16

happen time:  Time Processed (UTC): 6:07:46.941 pm, Wed, Feb 22, 2023  (almost everyday around 6:07:46.941 pm)

**Comment by Mike-Android-Chowbus** [comment] 2023-02-23 18:04
` " the next time you encounter a reboot I could check our device logs to verify this is the culprit. "  `

what does mean ? It means after I upgrade to 2.17.1 , then I encounter a reboot , I notice you to check or you can check yourself , then add this reader to the white-list ?

**Comment by chr-stripe** [comment] 2023-02-23 18:06
I would just be able to check myself that when the device disconnected unexpectedly (after upgrading the SDK to 2.17.1), that it would have been caused by the daily system integrity reboot on the M2.

Since the reboot is for ensuring the long-term performance of the M2, there is no whitelist to opt in to disabling this.

**Comment by Mike-Android-Chowbus** [comment] 2023-02-24 02:03
> I would just be able to check myself that when the device disconnected unexpectedly (after upgrading the SDK to 2.17.1), that it would have been caused by the daily system integrity reboot on the M2.
> 
> Since the reboot is for ensuring the long-term performance of the M2, there is no whitelist to opt in to disabling this.

So if I upgrade to the  2.17.1, I will do not  meet this trouble ?

**Comment by chr-stripe** [comment] 2023-02-24 06:58
No, regardless of which SDK version you are using, the M2 reader **will** reboot once every 24 hours. The only difference with 2.17.1 is that we start to measure internally _if_ when you get an `onUnexpectedReaderDisconnect()`, if it was because of this daily scheduled reboot.

**Comment by Mike-Android-Chow** [comment] 2023-02-24 08:02
> No, regardless of which SDK version you are using, the M2 reader **will** reboot once every 24 hours. The only difference with 2.17.1 is that we start to measure internally _if_ when you get an `onUnexpectedReaderDisconnect()`, if it was because of this daily scheduled reboot.

 You can get the log ,but  what do we get If I upgrade to the 2.17.1 ?

**Comment by Mike-Android-Chow** [comment] 2023-02-24 08:17
If I must reboot , Can you control the reboot time ? If you can control please let the reboot happen at the middleNight , not the business time ,it brings many troubles for the users

**Comment by chr-stripe** [comment] 2023-02-24 08:31
> You can get the log ,but what do we get If I upgrade to the 2.17.1 ?

Please review [the changelog](https://github.com/stripe/stripe-terminal-android/blob/master/CHANGELOG.md) for a list of the major highlights in each version.

> If it must reboot , Can you control the reboot time ? If you can control please let the reboot happen at the middleNight , not the business time ,it brings many troubles for the users

Unfortunately no, we cannot control the exact time. The reboot will always take place about 24 hours since it was last turned on. However, you can use that information to manually restart the reader at/before your own start of business if you wish to ensure that it won't automatically restart for the next 24 hours.

**Comment by Mike-Android-Chow** [comment] 2023-02-24 08:34
> > You can get the log ,but what do we get If I upgrade to the 2.17.1 ?
> 
> Please review [the changelog](https://github.com/stripe/stripe-terminal-android/blob/master/CHANGELOG.md) for a list of the major highlights in each version.
> 
> > If it must reboot , Can you control the reboot time ? If you can control please let the reboot happen at the middleNight , not the business time ,it brings many troubles for the users
> 
> Unfortunately no, we cannot control the exact time. The reboot will always take place about 24 hours since it was last turned on. However, you can use that information to manually restart the reader at/before your own start of business if you wish to ensure that it won't automatically restart for the next 24 hours.

got it ,thanks

**Comment by chr-stripe** [comment] 2023-02-27 21:06
1. The reboot should only take a few seconds, it is not long.

2. It's hard to say whether your reconnect logic is working or not without seeing 1) the code itself, and 2) logs from your application around the time of the reader reboot. As for whether this would be fixed by upgrading to 2.17.1, it's also hard to say. However, there should be no harm in updating to the latest version, which always contains the latest bug fixes and feature enhancements.

**Comment by chr-stripe** [comment] 2023-03-03 20:58
@Mike-Android-Chow I'm going to close this issue since the root cause of your daily reboots has likely been identified and is expected behaviour for the M2 reader. If you have any other issues please feel free to let me know!

**Closed by chr-stripe** 2023-03-03 20:58 UTC
