### ISSUE TITLE
Connect reader failed unexpectedly . Error: UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR

### ISSUE THREAD

**Issue by amrishkakadiya** [stripe/stripe-terminal-android#160] opened 2021-09-07 11:28 UTC
## Summary

I am trying to connect WISEPAD 3. In simulation it works fine but when I try with real device I am getting following error code in **Terminal Exception**  `UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR`

`com.stripe.stripeterminal.external.models.TerminalException: Connect reader failed unexpectedly`

## Code to reproduce

Here is my code snippet.

    Reader stripeReader;
    private void connectReader(Reader reader, String locationId) {
        sendMessage("Connecting to terminal...", 0);
        stripeReader = reader;
        sendMessage("Connecting to terminal::" + reader.getLabel() + " ID:" + reader.getId() + " LocationID: " + locationId, 0);
        ConnectionConfiguration.BluetoothConnectionConfiguration connectionConfig =
                new ConnectionConfiguration.BluetoothConnectionConfiguration(locationId);

        Terminal.getInstance().connectBluetoothReader(reader, connectionConfig, new BluetoothReaderListener() {
            @Override
            public void onStartInstallingUpdate(@NotNull ReaderSoftwareUpdate readerSoftwareUpdate, @org.jetbrains.annotations.Nullable Cancelable cancelable) {
                sendMessage("Update installing", 0);
            }

            @Override
            public void onReportReaderSoftwareUpdateProgress(float v) {
                sendMessage("Updating " + MyApp.df.format(v * 100) + "%", 0);
            }

            @Override
            public void onFinishInstallingUpdate(@org.jetbrains.annotations.Nullable ReaderSoftwareUpdate readerSoftwareUpdate, @org.jetbrains.annotations.Nullable TerminalException e) {
                sendMessage("Finishing Updating", 0);
            }

            @Override
            public void onReportAvailableUpdate(@NotNull ReaderSoftwareUpdate readerSoftwareUpdate) {
                sendMessage("Update available", 0);
            }

            @Override
            public void onRequestReaderInput(@NotNull ReaderInputOptions readerInputOptions) {

            }

            @Override
            public void onRequestReaderDisplayMessage(@NotNull ReaderDisplayMessage readerDisplayMessage) {
                sendMessage("Message\n" + readerDisplayMessage.toString(), 0);
            }

            @Override
            public void onReportReaderEvent(@NotNull ReaderEvent readerEvent) {

            }

            @Override
            public void onReportLowBatteryWarning() {
                sendMessage("Low battery please recharge the reader", 0);
            }
        }, new ReaderCallback() {
            @Override
            public void onSuccess(Reader r) {
                cardReader.s_terminal_id = r.getId();
                createPaymentIntent();
            }

            @Override
            public void onFailure(TerminalException e) {
                e.printStackTrace();
                sendMessage("Terminal Exception\nCode:" + e.getErrorCode().toString() + "\n" + e.getErrorMessage() + "\n" + (e.getApiError() == null ? "" : (e.getApiError().getMessage())) + "\n" + new Gson().toJson(stripeReader), 2);

            }
        });

    }`
## Android version

`7.1`

## SDK version

`"com.stripe:stripeterminal:2.2.0"`

I am getting following exception

I dont have device with me I am testing over call so any suggestions or fixes for this issue?

**Comment by dhenry-stripe** [comment] 2021-09-07 21:52
@amrishkakadiya what does the list of `Reader` objects that you receive during discovery contain? It looks like the reader you're passing to `connectBluetoothReader` has a null `device` value.

**Comment by amrishkakadiya** [comment] 2021-09-08 03:48
@dhenry-stripe  I am `Reader `object contain

`{"deviceType":"WISEPAD_3","hardwareVersion":"unknown","isSimulated":false,"locationStatus":"NOT_SET","serialNumber":"WPC323053000548","softwareVersion":"unknown"}`

```
com.stripe.stripeterminal.external.models.TerminalException: Connect reader failed unexpectedly
	at com.stripe.stripeterminal.adapter.BbposAdapter$ConnectReaderOperation.execute(BbposAdapter.kt:885)
	at com.stripe.stripeterminal.adapter.BbposAdapter.connectReader(BbposAdapter.kt:244)
	at com.stripe.stripeterminal.adapter.ProxyAdapter.connectReader(ProxyAdapter.kt:110)
	at com.stripe.stripeterminal.TerminalSession$ConnectReaderOperation.execute(TerminalSession.kt:787)
	at com.stripe.stripeterminal.TerminalSession$ExternalOperation.run$core_publish(TerminalSession.kt:453)
	at com.stripe.stripeterminal.TerminalSession.enqueueOperation$lambda-2(TerminalSession.kt:350)
	at com.stripe.stripeterminal.TerminalSession.lambda$JON2uE3bqI6fqJ9Sw06Ciz8JRZw(Unknown Source:0)
	at com.stripe.stripeterminal.-$$Lambda$TerminalSession$JON2uE3bqI6fqJ9Sw06Ciz8JRZw.run(Unknown Source:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

and this is the exception I am getting.

**Comment by dhenry-stripe** [comment] 2021-09-08 19:44
@amrishkakadiya thanks for confirming. The reader object should contain a `device` field with a mac address. Can you please post the code you're using to discover the reader and any transformations you apply to it prior to passing it to `connectBluetoothReader`?

**Comment by amrishkakadiya** [comment] 2021-09-09 04:04
@dhenry-stripe  okay, please find code snippet for discovery 
```
private void initialize() {
        try {
            if (!Terminal.isInitialized()) {
                Terminal.initTerminal(getActivity(), LogLevel.VERBOSE, new CustomTokenProvider(cardReader.s_location_id, merchantBusinesses.id), new CustomTerminalEventListener(getActivity()));
            } else {
                LogUtils.e("Terminal already initialized");
            }
        } catch (TerminalException e) {
            if (dialogDismissListener != null)
                dialogDismissListener.onDialogDismiss("Location services are required in order to initialize the Terminal");
            dismiss();
        }
        discoverReaders();
    }

//Simulated
    boolean isSimulated = false;

    private void discoverReaders() {
        LogUtils.e("Discovering Readers");
        //Charges declined 4000000000000002
        //Success Discover Type 6011111111111117
        if (isSimulated) {
            SimulatorConfiguration simulatorConfiguration = new SimulatorConfiguration(SimulateReaderUpdate.RANDOM, new SimulatedCard("4000000000000002"));
            Terminal.getInstance().setSimulatorConfiguration(simulatorConfiguration);
        }
        sendMessage("Discovering readers...", 0);
        DiscoveryConfiguration discoveryConfig = new DiscoveryConfiguration(0, DiscoveryMethod.BLUETOOTH_SCAN, isSimulated);
        cancelableDiscovery = Terminal.getInstance().discoverReaders(discoveryConfig, discoveryListener, callback);

    }
```

```

private MerchantCardReader cardReader;
    final DiscoveryListener discoveryListener = readers -> {
        ArrayList<Reader> readerArrayList = new ArrayList<>(readers);
//        cancelableDiscovery.isCompleted();
        readersFound = readerArrayList.size() > 0;
        if (readerSelectionDisplayed) return;
        if (readersFound) {
            if (cardReader.s_terminal_id != null) {
                for (Reader r : readers) {
                    if (r.getId() != null && r.getId().equals(cardReader.s_terminal_id)) {
                        String locationId = cardReader.s_location_id;
                        if (r.getLocation() != null)
                            locationId = r.getLocation().getId();
                        connectReader(r, locationId);
                        break;
                    }
                }
            } else {
                //Show discovered bluetooth readers
                sendMessage("Please select terminal", 0);
                SelectCardReaderDialogFragment selectCardReaderDialogFragment = SelectCardReaderDialogFragment.getInstance(readerArrayList, true);
                selectCardReaderDialogFragment.show(getChildFragmentManager(), "card_readers");
                selectCardReaderDialogFragment.setCancelable(false);
                selectCardReaderDialogFragment.setDialogDismissListener(o -> {
                    if (o instanceof Reader) {
                        Reader reader = (Reader) o;
                        String locationId = cardReader.s_location_id;
                        if (reader.getLocation() != null)
                            locationId = reader.getLocation().getId();
                        connectReader((Reader) o, locationId);
                    } else {
                        if (dialogDismissListener != null) {
                            dialogDismissListener.onDialogDismiss(null);
                        }
                        dismiss();
                    }
                });
            }
            readerSelectionDisplayed = true;
        }

    };
```

Here `MerchantCardReader`  is my own object which have `s_location_id` key returned from my database stored with stripe account locations.

**Comment by dhenry-stripe** [comment] 2021-09-09 18:57
Thanks @amrishkakadiya, this all looks fine. I see that there is also an ongoing support ticket for this issue [0]. I'm going to close this issue for now to avoid duplicated effort. If the resolution of the support ticket doesn't solve the problem, feel free to re-open this.

[0] https://stripe.zendesk.com/agent/tickets/19060389

**Closed by dhenry-stripe** 2021-09-09 18:57 UTC

**Comment by amrishkakadiya** [comment] 2021-09-20 13:37
@dhenry-stripe  Support ticket could not help me, can you help me find out what is wrong with the code. Exception only shows SDK_ERROR and sdk's BbposAdapter.kt file's exception.


I am getting this two exceptions.
```

2021-09-20 14:16:16.040 26924-26924/com.tiffintompartner W/System.err: java.lang.ClassNotFoundException: com.stripe.cots.CotsAdapterProvider
2021-09-20 14:16:16.040 26924-26924/com.tiffintompartner W/System.err:     at java.lang.Class.classForName(Native Method)
2021-09-20 14:16:16.040 26924-26924/com.tiffintompartner W/System.err:     at java.lang.Class.forName(Class.java:454)
2021-09-20 14:16:16.040 26924-26924/com.tiffintompartner W/System.err:     at java.lang.Class.forName(Class.java:379)
2021-09-20 14:16:16.040 26924-26924/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.dagger.CotsModule.provideCotsAdapter(CotsModule.kt:46)
2021-09-20 14:16:16.040 26924-26924/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.dagger.CotsModule_ProvideCotsAdapterFactory.provideCotsAdapter(CotsModule_ProvideCotsAdapterFactory.java:39)
2021-09-20 14:16:16.040 26924-26924/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.dagger.CotsModule_ProvideCotsAdapterFactory.get(CotsModule_ProvideCotsAdapterFactory.java:29)
2021-09-20 14:16:16.040 26924-26924/com.tiffintompartner W/System.err:     at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
2021-09-20 14:16:16.040 26924-26924/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.dagger.CotsModule_ProvideCotsProxyAdapterFactory.get(CotsModule_ProvideCotsProxyAdapterFactory.java:49)
2021-09-20 14:16:16.040 26924-26924/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.dagger.CotsModule_ProvideCotsProxyAdapterFactory.get(CotsModule_ProvideCotsProxyAdapterFactory.java:14)
2021-09-20 14:16:16.040 26924-26924/com.tiffintompartner W/System.err:     at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
2021-09-20 14:16:16.040 26924-26924/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.dagger.TerminalModule_ProvideProxyAdapterFactory.get(TerminalModule_ProvideProxyAdapterFactory.java:55)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.dagger.TerminalModule_ProvideProxyAdapterFactory.get(TerminalModule_ProvideProxyAdapterFactory.java:17)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.TerminalSession_Factory.get(TerminalSession_Factory.java:65)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.TerminalSession_Factory.get(TerminalSession_Factory.java:15)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.Terminal_Factory.get(Terminal_Factory.java:31)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.Terminal_Factory.get(Terminal_Factory.java:9)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.dagger.DaggerTerminalComponent.getTerminal(DaggerTerminalComponent.java:741)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.Terminal$Companion.initTerminal(Terminal.kt:811)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.Terminal.initTerminal(Unknown Source:2)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at com.tiffintom.partner.fragments.StripeBluetoothCardReaderPaymentFragment.initialize(StripeBluetoothCardReaderPaymentFragment.java:152)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at com.tiffintom.partner.fragments.StripeBluetoothCardReaderPaymentFragment.onViewCreated(StripeBluetoothCardReaderPaymentFragment.java:124)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-09-20 14:16:16.041 26924-26924/com.tiffintompartner W/System.err:     at android.os.Looper.loop(Looper.java:246)
2021-09-20 14:16:16.042 26924-26924/com.tiffintompartner W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8577)
2021-09-20 14:16:16.042 26924-26924/com.tiffintompartner W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-09-20 14:16:16.042 26924-26924/com.tiffintompartner W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
2021-09-20 14:16:16.042 26924-26924/com.tiffintompartner W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-09-20 14:16:16.042 26924-26924/com.tiffintompartner W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.stripe.cots.CotsAdapterProvider" on path: DexPathList[[dex file "/data/data/com.tiffintompartner/code_cache/.overlay/base.apk/classes2.dex", zip file "/data/app/~~X0eohK86ap3XW2PFjlIoJQ==/com.tiffintompartner-7x48F5ImpYTybWY_qmHf5A==/base.apk"],nativeLibraryDirectories=[/data/app/~~X0eohK86ap3XW2PFjlIoJQ==/com.tiffintompartner-7x48F5ImpYTybWY_qmHf5A==/lib/arm64, /data/app/~~X0eohK86ap3XW2PFjlIoJQ==/com.tiffintompartner-7x48F5ImpYTybWY_qmHf5A==/base.apk!/lib/arm64-v8a, /system/lib64]]
2021-09-20 14:16:16.042 26924-26924/com.tiffintompartner W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
2021-09-20 14:16:16.042 26924-26924/com.tiffintompartner W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2021-09-20 14:16:16.042 26924-26924/com.tiffintompartner W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2021-09-20 14:16:16.042 26924-26924/com.tiffintompartner W/System.err: 	... 38 more

```

And this one also
```

2021-09-20 14:18:56.108 27613-27979/com.tiffintompartner W/System.err: com.stripe.stripeterminal.external.models.TerminalException: Connect reader failed unexpectedly
2021-09-20 14:18:56.108 27613-27979/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.adapter.BbposAdapter$ConnectReaderOperation.execute(BbposAdapter.kt:885)
2021-09-20 14:18:56.108 27613-27979/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.adapter.BbposAdapter.connectReader(BbposAdapter.kt:244)
2021-09-20 14:18:56.108 27613-27979/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.adapter.ProxyAdapter.connectReader(ProxyAdapter.kt:110)
2021-09-20 14:18:56.108 27613-27979/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.TerminalSession$ConnectReaderOperation.execute(TerminalSession.kt:787)
2021-09-20 14:18:56.108 27613-27979/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.TerminalSession$ExternalOperation.run$core_publish(TerminalSession.kt:453)
2021-09-20 14:18:56.109 27613-27979/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.TerminalSession.enqueueOperation$lambda-2(TerminalSession.kt:350)
2021-09-20 14:18:56.109 27613-27979/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.TerminalSession.lambda$JON2uE3bqI6fqJ9Sw06Ciz8JRZw(Unknown Source:0)
2021-09-20 14:18:56.109 27613-27979/com.tiffintompartner W/System.err:     at com.stripe.stripeterminal.-$$Lambda$TerminalSession$JON2uE3bqI6fqJ9Sw06Ciz8JRZw.run(Unknown Source:4)
2021-09-20 14:18:56.109 27613-27979/com.tiffintompartner W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2021-09-20 14:18:56.109 27613-27979/com.tiffintompartner W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-09-20 14:18:56.109 27613-27979/com.tiffintompartner W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-09-20 14:18:56.109 27613-27979/com.tiffintompartner W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-09-20 14:18:56.109 27613-27979/com.tiffintompartner W/System.err:     at java.lang.Thread.run(Thread.java:923)
```

Reader object has this following details

` {"deviceType":"WISEPAD_3",
"hardwareVersion":"unknown",
"isSimulated":false,
"location":
{"address":{"city":"WALSALL","country":"GB","line1":"12 Little Caldmore","line2":"","postalCode":"WS13RA","state":"West Midlands"},
"displayName":"poasd",
"id":"tml_ERm2oA0tcaokTd",
"livemode":false,
"metadata":{"connected_account":"acct_1JNAqNRLIFbBKLQd"}},
"locationStatus":"SET",
"serialNumber":"WPC323053000545",
"softwareVersion":"unknown"}`
    

Same things run with demo application but not with my code. So can you check what is wrong with my code? 

Thank you.

**Comment by dhenry-stripe** [comment] 2021-09-20 14:03
@amrishkakadiya the first stack trace isn't an issue. You can ignore it. If you update to version 2.3.0 it will go away. The second issue is an integration issue. I don't see anything in the code you provided that indicates why you're seeing this error. The fact that the demo application works though indicates that the issue is in your code somewhere. I suggest you go back through and compare the differences between your application and the demo application to find the source of the issue. Failing that, you could try submitting your entire integration codebase via a support ticket.

**Comment by amrishkakadiya** [comment] 2021-09-21 12:43
@dhenry-stripe  Thank you for helping, I found the error . I was trying to connect reader in background thread. It requires to run on UI thread. I think exception should mention this kind of exception message clearly.

**Comment by dhenry-stripe** [comment] 2021-09-22 15:23
Fantastic! I'm glad to hear that @amrishkakadiya. 

> I was trying to connect reader in background thread. It requires to run on UI thread. I think exception should mention this kind of exception message clearly.

Fair point. I'll chat with my team about making this more explicit.
