### ISSUE TITLE
Illegal State Exception When Processing Payment

### ISSUE THREAD

**Issue by legomanaustralia** [stripe/stripe-terminal-android#30] opened 2019-05-14 06:07 UTC
We're also seeing this get thrown when we try to process a payment as well, this results in an app crash, it says the device is connected when it looks like it actually isn't.

`java.lang.IllegalStateException: Unexpected operation in progress. Expected: class com.stripe.stripeterminal.BbposBluetoothAdapter$CollectPaymentMethodOperation, found: class com.stripe.stripeterminal.BbposBluetoothAdapter$ConnectReaderOperation
        at com.stripe.stripeterminal.BbposBluetoothAdapter.validateOperationInProgress(BbposBluetoothAdapter.java:324)
        at com.stripe.stripeterminal.BbposBluetoothAdapter.onCancelCollectPaymentMethod(BbposBluetoothAdapter.java:164)
        at com.stripe.stripeterminal.BbposDeviceControllerListener.onReturnCancelCheckCardResult(BbposDeviceControllerListener.java:131)
        at com.bbposstripe.bbdevice.BBDeviceController$58.run(SourceFile:3281)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5637)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)`

**Comment by danwaters-stripe** [comment] 2019-05-15 00:42
Hmm, it does look like that's what's happening. Just to verify: are you waiting for the `onSuccess` method of your connectReader `Callback` before you call collectPaymentMethod? Or are you calling it as soon as you see `onConnectionStatusChange(CONNECTED)`? If you're doing the latter, I could see this problem arising. 

If not, do you have any more logs of the full transaction that you could send me? Or at least a timestamp or PaymentIntent ID that I can use to help debug? Any info you have would be helpful. Thanks!

**Comment by anton8900** [comment] 2019-05-15 06:09
So this error when previous time discoverReaders don't ends succesfully, it was too long and i finished cancelable, then i am trying to connect again but getConnectedReader returns connected reader, then i starting readReusableCard and it is too long again and when i am trying to cancel cancelable and all crashes with this error

**Comment by anton8900** [comment] 2019-05-15 06:12
So we can't to stuck user in connect activity if it is too long (more than 3 minutes). If to stop application and try again all begins to work

**Comment by anton8900** [comment] 2019-05-15 06:14
I suggest that it is some error with connecting via bluetooth

**Comment by danwaters-stripe** [comment] 2019-05-15 17:18
Do you have complete logs (with `LogLevel.VERBOSE`) for this transaction? If not, could you describe the flow you're seeing in more detail? What happens when you call `cancel` on the discoverReaders Cancelable? Do you get an error, or is that canceled successfully? Any more information would be helpful as I try to reproduce this.

**Comment by anton8900** [comment] 2019-05-16 08:02
so i am getteng terminal instance using this method can you check it
`private Terminal getTerminal(Application application) {
        Terminal instance = null;

        try {
            Terminal.initTerminal(application.getApplicationContext(), LogLevel.VERBOSE, new TokenProvider(), terminalEventListener);
        } catch (Exception ex){
            ex.printStackTrace();
            getViewState().showErrorMessage("Initializing stripe failed");
        }

        try {
            instance = Terminal.getInstance();
        } catch (Exception ex) {
            ex.printStackTrace();
            getViewState().showErrorMessage("Initializing stripe failed");
        }

        return instance;
    }
`

**Comment by anton8900** [comment] 2019-05-16 08:07
you can check verbose logs here
https://drive.google.com/file/d/1UaReiZ4xhbpUsGQSDcp7dQJdtFOhGe58/view?usp=sharing

**Comment by anton8900** [comment] 2019-05-16 08:09
this exception is in the end of file

**Comment by anton8900** [comment] 2019-05-16 08:24
i am not sure that it is what you need but it occures when reader was connected to power and light was violet

**Comment by danwaters-stripe** [comment] 2019-05-16 17:05
Thanks for the logs. However, I don't see this exception (or any Stripe logs) in the document you sent me. Is there another document with more detail?

**Comment by anton8900** [comment] 2019-05-17 05:38
why you don't see exception?

java.lang.IllegalStateException: Unexpected operation in progress. Expected: class com.stripe.stripeterminal.BbposBluetoothAdapter$DiscoverReadersOperation, found: class com.stripe.stripeterminal.BbposBluetoothAdapter$CheckForUpdateOperation
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3953)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3919)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3893)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3867)
        at android.app.ActivityThread.-wrap15(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6548)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
     Caused by: java.lang.IllegalStateException: Unexpected operation in progress. Expected: class com.stripe.stripeterminal.BbposBluetoothAdapter$DiscoverReadersOperation, found: class com.stripe.stripeterminal.BbposBluetoothAdapter$CheckForUpdateOperation
        at com.stripe.stripeterminal.BbposBluetoothAdapter.validateOperationInProgress(BbposBluetoothAdapter.java:324)
        at com.stripe.stripeterminal.BbposBluetoothAdapter.cancelDiscoverReaders(BbposBluetoothAdapter.java:77)
        at com.stripe.stripeterminal.MasterAdapter.cancelDiscoverReaders(MasterAdapter.java:35)
        at com.stripe.stripeterminal.TerminalSession$DiscoverReadersOperation.startCancel(TerminalSession.java:652)
        at com.stripe.stripeterminal.Cancelable.cancel(Cancelable.java:30)
        at au.com.ticketbooth.rfid.android.mvp.presenter.settings.StripeReaderConnectPresenter.stopConnecting(StripeReaderConnectPresenter.java:148)
        at au.com.ticketbooth.rfid.android.ui.activities.settings.stripe.StripeReaderConnectActivity.onPause(StripeReaderConnectActivity.java:96)
        at android.app.Activity.performPause(Activity.java:7167)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1408)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3942)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3919) 
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3893) 
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3867) 
        at android.app.ActivityThread.-wrap15(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6548) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857) 

copied it from the end of the file that i have send

**Comment by danwaters-stripe** [comment] 2019-05-17 17:42
Sorry for the previous comment, Google docs only loaded a portion of the logs at first. After looking at the entire log, are you attempting to run multiple instances of the Terminal class at once? I see a number of these errors:

```
2019-05-16 15:32:36.787 5133-5133/au.com.ticketbooth.rfid.android W/System.err: java.lang.IllegalStateException: You can only call initTerminal *before* requesting the Terminal instance for the first time. If you are trying to switch accounts in your app, refer to the documentation for the `clearCachedCredentials` method.
2019-05-16 15:32:36.787 5133-5133/au.com.ticketbooth.rfid.android W/System.err:     at com.stripe.stripeterminal.Terminal.initTerminal(Terminal.java:39)
2019-05-16 15:32:36.788 5133-5133/au.com.ticketbooth.rfid.android W/System.err:     at au.com.ticketbooth.rfid.android.mvp.presenter.settings.StripeReaderConnectPresenter.getTerminal(StripeReaderConnectPresenter.java:282)
2019-05-16 15:32:36.788 5133-5133/au.com.ticketbooth.rfid.android W/System.err:     at au.com.ticketbooth.rfid.android.mvp.presenter.settings.StripeReaderConnectPresenter.tryToConnect(StripeReaderConnectPresenter.java:97)
2019-05-16 15:32:36.788 5133-5133/au.com.ticketbooth.rfid.android W/System.err:     at au.com.ticketbooth.rfid.android.ui.activities.settings.stripe.StripeReaderConnectActivity.onTryAgainClicked(StripeReaderConnectActivity.java:46)
2019-05-16 15:32:36.788 5133-5133/au.com.ticketbooth.rfid.android W/System.err:     at au.com.ticketbooth.rfid.android.ui.activities.settings.stripe.StripeReaderConnectActivity.onResume(StripeReaderConnectActivity.java:81)
2019-05-16 15:32:36.789 5133-5133/au.com.ticketbooth.rfid.android W/System.err:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
2019-05-16 15:32:36.789 5133-5133/au.com.ticketbooth.rfid.android W/System.err:     at android.app.Activity.performResume(Activity.java:7131)
2019-05-16 15:32:36.789 5133-5133/au.com.ticketbooth.rfid.android W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3597)
2019-05-16 15:32:36.789 5133-5133/au.com.ticketbooth.rfid.android W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3662)
2019-05-16 15:32:36.790 5133-5133/au.com.ticketbooth.rfid.android W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
2019-05-16 15:32:36.790 5133-5133/au.com.ticketbooth.rfid.android W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2019-05-16 15:32:36.790 5133-5133/au.com.ticketbooth.rfid.android W/System.err:     at android.os.Looper.loop(Looper.java:164)
2019-05-16 15:32:36.790 5133-5133/au.com.ticketbooth.rfid.android W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6548)
2019-05-16 15:32:36.791 5133-5133/au.com.ticketbooth.rfid.android W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-05-16 15:32:36.791 5133-5133/au.com.ticketbooth.rfid.android W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2019-05-16 15:32:36.791 5133-5133/au.com.ticketbooth.rfid.android W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

Then it looks like most of your calls are called twice in a row. Like here:
```
2019-05-16 15:32:36.775 5133-5133/au.com.ticketbooth.rfid.android D/Log: class=Terminal message=discoverReaders
2019-05-16 15:32:36.799 5133-5133/au.com.ticketbooth.rfid.android D/Log: class=Terminal message=discoverReaders
2019-05-16 15:32:36.844 5133-5472/au.com.ticketbooth.rfid.android D/Log: class=BbposBluetoothAdapter message=discoverReaders
2019-05-16 15:32:37.133 5133-5133/au.com.ticketbooth.rfid.android D/Log: class=BbposDeviceControllerListener message="onBTReturnScanResults([List: {CHB204650000648}])"
2019-05-16 15:32:37.137 5133-5133/au.com.ticketbooth.rfid.android D/Log: class=Terminal message=connectReader
2019-05-16 15:32:37.168 5133-5133/au.com.ticketbooth.rfid.android D/Log: class=Terminal message=connectReader
```

I believe that's the root of your problem. Only one instance of Terminal can exist at any time, so if you call `initTerminal` twice, the second one will fail. I hope that helps!

**Comment by anton8900** [comment] 2019-05-20 15:30
Please check this code i am using

try {
        Terminal.initTerminal(application.getApplicationContext(), LogLevel.VERBOSE, new TokenProvider(),
terminalEventListener);
    } catch (Exception ex){
        ex.printStackTrace();
    }

this error successfully catched by this block 

and throwed here

/**
     * Initializes a terminal for the given context.
     *
     * @param applicationContext The {@link Context} of the running Android application
     * @param logLevel The level of logging verbosity to use in this Terminal instance
     * @param tokenProvider The {@link ConnectionTokenProvider} to use when a new token is needed
     * @param listener The {@link TerminalListener} to inform of events in the Terminal lifecycle
     */
    public static void initTerminal(Context applicationContext,
                                    LogLevel logLevel,
                                    ConnectionTokenProvider tokenProvider,
                                    @Nonnull TerminalListener listener) throws TerminalException {
        if (instance != null) {
            throw new IllegalStateException("You can only call initTerminal *before* requesting " +
                    "the Terminal instance for the first time. If you are trying to switch " +
                    "accounts in your app, refer to the documentation for the " +
                    "`clearCachedCredentials` method.");
        }
...

So can be only one instance and there is no any error, You need to search error in different place

**Comment by anton8900** [comment] 2019-05-20 15:31
I have already catched this error on my level, so you can close this issue

**Closed** 2019-05-29 17:53 UTC
