### ISSUE TITLE
Need onRequestDisplayText when receive onRequestReaderDisplayMessage(Try Another Read Method)

### ISSUE THREAD

**Issue by ohmyleonia** [stripe/stripe-terminal-android#195] opened 2021-12-29 05:15 UTC
## Summary

When customer using credit card to pay, we sometimes received message from BBPOS/M2 with _Try Another Read Method_. But we don't know how the read method didn't work.
We can see in Stripe it does have _onRequestDisplayText_ like below log. Could we have the same when using SDK?

2021-12-29 11:07:16.065 I/StripeTerminal: class=BBPOSTransactionListener message="onRequestDisplayText NOT_ICC_CARD"
2021-12-29 11:07:16.065 I/CombinedKernelInterface: handleCardStatus CARD_NOT_WORKING
2021-12-29 11:07:16.066 I/StripeTerminal: class=TransactionManager message="handleCardStatus CARD_NOT_WORKING"
2021-12-29 11:07:16.067 I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: COLLECT -> PAYMENT_PROCESSING: Contact - bad insert"
2021-12-29 11:07:16.068 I/StripeTerminal: class=ProxyReaderListener message="onRequestReaderDisplayMessage(Try Another Read Method)"
2021-12-29 11:07:16.127 I/StripeTerminal: class=BBPOSTransactionListener message="onRequestDisplayText INSERT_SWIPE_OR_TRY_ANOTHER_CARD"
2021-12-29 11:07:19.095 I/StripeTerminal: class=BBPOSTransactionListener message="onRequestDisplayText PRESENT_CARD"
2021-12-29 11:07:19.140 I/StripeTerminal: class=BBPOSTransactionListener message="onWaitingForCard SWIPE_OR_INSERT_OR_TAP"
2021-12-29 11:07:19.141 I/StripeTerminal: class=ProxyReaderListener message="onRequestReaderInput(Swipe / Insert / Tap)"

## Android version

9
## Impacted devices (Android devices or readers)

BBPOS  M2
## SDK version

2.5.2

**Comment by dhenry-stripe** [comment] 2022-01-05 06:09
Hi @ohmyleonia, `Try Another Read Method` received via `ReaderListener.onRequestReaderDisplayMessage` is caused by one of two errors:

|name|description|
| ----------- | ----------- |
|CTL_APP_NOT_SUPPORTED|The application does not support contactless.|
|NOT_ICC_CARD|A non-chip card is detected.|

Are you requesting that we surface the underlying errors through the SDK? If so, can you please explain how this will solve your use case?

**Comment by ohmyleonia** [comment] 2022-01-07 03:13
@dhenry-stripe But the strange thing was the card support chipping, but we receive error of NOT_ICC_CARD on M2. If we change to BBPOS, the card can be chipped safely. 
Now we can see this issue is actually related to issue#194 https://github.com/stripe/stripe-terminal-android/issues/194. Issue#194 should be fixed ASAP.

**Comment by chr-stripe** [comment] 2022-08-08 21:52
@ohmyleonia if the underlying issue is caused by #194 instead, is it safe to close this ticket or is there something else that needs to be looked into further here?

**Closed** 2022-08-29 12:55 UTC
