### ISSUE TITLE
Payment Method collection not canceled when the terminal disconnects - USB connection

### ISSUE THREAD

**Issue by giovanniandreuzza** [stripe/stripe-terminal-android#365] opened 2023-09-01 08:59 UTC
## Summary
My app connects to the terminal via USB (WisePad 3), presents the payment on it but when the terminal disconnects I still see the payment presented. To exit from it I have to press the x button on the terminal.

## Android version
Android 7.1.1

## SDK version
2.23.1

## Other information
The way I manage to disconnect the terminal from my device is by connecting my mac on the device via USB

**Comment by bperez-stripe** [comment] 2024-01-26 17:47
Hi @giovanniandreuzza, we believe this is the same issue as #402.

**Comment by billfinn-stripe** [comment] 2024-04-10 00:32
Hi @giovanniandreuzza -- I'm going to close this issue as a duplicate of 402. Feel free to reopen if you believe they are different.

**Closed by billfinn-stripe** 2024-04-10 00:32 UTC
