### ISSUE TITLE
Unable to import com.stripe.stripeterminal in new project

### ISSUE THREAD

**Issue by rscott78** [stripe/stripe-terminal-android#85] opened 2019-12-23 21:02 UTC
I created a brand new Kotlin project, then following the steps in the Getting Started Guide.  I added the dependency `implementation "com.stripe:stripeterminal:1.0.0"`, but at the point where I attempt to `import com.stripe.stripeterminal`, Android Studio behaves as if no package exists and I get an error saying 'packages cannot be imported`.

I'm guessing this must be something simple that I'm missing, but I'm running into a wall. Any suggestions on what to try from here?

Android Studio 3.5.3
Build #AI-191.8026.42.35.6010548, built on November 15, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by hkstar** [comment] 2020-01-03 06:48
using java not kolin

**Comment by chander-stripe** [comment] 2020-01-23 17:48
Closing this, as it's a dupe of https://github.com/stripe/stripe-terminal-android/issues/73 - we're trying to investigate a solution to this now.

To be clear, it will compile - Android Studio (due to an Android Studio bug) just _thinks_ the class isn't there, so auto complete isn't working and it's highlighting as red.

**Closed by chander-stripe** 2020-01-23 17:48 UTC
