### ISSUE TITLE
Stripe registers ESP8266 CP2102 usb vendor/product ID in the usb tech filter, which wrongly triggers an USB assecories selection popup.

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [stripe/stripe-terminal-android#421] opened 2024-01-29 11:00 UTC
## Summary
Stripe registers ESP8266 CP2102 usb vendor/product ID in the usb tech filter, which wrongly triggers an USB assecories selection popup ( => com.stripe.stripeterminal.internal.common.usb.UsbEventReceiverActivity )

![signal-2024-01-29-115925](https://github.com/stripe/stripe-terminal-android/assets/10075/737d651f-54dd-4a71-b877-af2d47f829b1)

Is there any reason why stripe registeres in production for ESP8266 CP2102 Interfaces? We have our own hardware, and we don't want to have a misleading popup like this.

## Android version
Android 11

## Impacted devices (Android devices or readers)
No attached stripe hardware devices, only our own hardware implemented with ESP8266 wroom devices.

## SDK version
2.23.1

## Other information

```
2024-01-29 11:50:15.736  1744-2076  UsbHostManagerJNI       system_server                        E  Platform : helios | VID : 0x10c4 | PID : 0xea60 .
2024-01-29 11:50:15.737  1744-1744  UsbDeviceManager        system_server                        I  UsbDeviceManager.onReceive ACTION_USB_DEVICE_ATTACHED VID = 4292
2024-01-29 11:50:15.758  2068-2068  ResolverListAdapter     com.android.systemui                 I  Add DisplayResolveInfo component: ComponentInfo{at.myuser.myuser.android/at.myuser.myuser.android.core.UsbEventReceiverActivity}, intent component: ComponentInfo{at.myuser.myuser.android/at.myuser.myuser.android.core.UsbEventReceiverActivity}
2024-01-29 11:50:15.758  2068-2068  ResolverListAdapter     com.android.systemui                 I  Add DisplayResolveInfo component: ComponentInfo{at.myuser.myuser.android/com.stripe.stripeterminal.internal.common.usb.UsbEventReceiverActivity}, intent component: ComponentInfo{at.myuser.myuser.android/com.stripe.stripeterminal.internal.common.usb.UsbEventReceiverActivity}
```

**Comment by h0jeZvgoxFepBQ2C** [comment] 2024-02-19 19:51
Would be nice to get some feedback here from your developers!

**Comment by maxa-stripe** [comment] 2024-03-02 12:39
@h0jeZvgoxFepBQ2C Thank you for the report. I happen to have an ESP8266 with the same UART, and I attempted to reproduce the behavior you described using an app with the same Terminal SDK version as yours running on a Pixel 2 XL phone.

I did not observe the same behavior as you did when I connected the MCU to my phone: there was no popup, and no logs indicating that the Terminal SDK was even aware of the device. In addition, I confirmed that we ship the SDK with a filter that should preclude it from contacting USB devices other than those provided by Stripe:

```xml
<resources>
    <usb-device product-id="22352" vendor-id="11369" />
    <usb-device product-id="257" vendor-id="5538" />
</resources>
```

Could you provide any information about the Android device you're using? You mentioned that it's running Android 11 (same as my Pixel 2 XL), but that's not saying much considering that the OS could have come from an OEM. I noticed that my device printed logs that looked quite different from yours. This leads me to believe that the ROM you're using could be playing a role here.

Lastly, could I ask you to dump the Android manifest of your app and the associated USB filter XML? It's possible that the manifest merging process has somehow dropped our SDK's USB filters, which might lead to the behavior you're observing.

**Comment by dmatthews-stripe** [comment] 2024-03-15 16:01
Hi @h0jeZvgoxFepBQ2C , we were not able to reproduce this issue. If you are able to reproduce this issue with the information requested above, please feel free to re-open the ticket. We will be closing this ticket.

**Closed by dmatthews-stripe** 2024-03-15 16:01 UTC
