### ISSUE TITLE
Fatal Exception while discovering readers

### ISSUE THREAD

**Issue by ssavic** [stripe/stripe-terminal-android#283] opened 2022-12-20 16:10 UTC
## Summary
Runtime exception when discovering M2 readers.  Works fine if I use simulated devices, but when I switch to bluetooth device app crashes.

## Code to reproduce
<img width="927" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/1315382/208712879-3b2cea34-71e3-4787-86e9-59397158fb16.png">

## Android version
13.0

## Impacted devices (Android devices or readers)
Google Pixel 6A
M2 Reader

## SDK version
2.16.0

## Other information
<img width="1435" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/1315382/208712903-6b5760fe-d2d2-41e7-8307-114d4f07f3ac.png">

**Comment by chr-stripe** [comment] 2022-12-20 16:49
This looks to be a similar issue as #278, though not necessarily being caused by the Square Reader SDK in your case as well. 

This will be fixed in 2.17.0, which will likely be released in late January 2023.

**Comment by ssavic** [comment] 2022-12-20 19:55
Thanks!

**Comment by chr-stripe** [comment] 2022-12-20 20:01
I'll close this issue since it seems like a duplicate of the other.

**Closed by chr-stripe** 2022-12-20 20:01 UTC
