### ISSUE TITLE
Terminal Not Calling ReaderCallback Delegate After ConnectBluetoothReader

### ISSUE THREAD

**Issue by chris-oswald** [stripe/stripe-terminal-android#188] opened 2021-12-07 03:49 UTC
## Summary
The reader connection callback delegate isn't called after a successful connection. The "OnConnectionStatusChange" is called and the connection is "CONNECTED", but the OnSuccess delegate is never invoked in the ReaderConnectionCallback. The odd thing is if the reader is off or the connection times out the OnFailure delegate is called correctly.

I'm building Xamarin (C#) bindings for the 2.5.2 terminal. I've successfully done this for the 1.X versions, and suspect I'm missing something simple in the binding (I'm sure it's me). Maybe a library or something obvious that's called in the connection. 

Can you look at my logs from the reader (see below) and see if anything looks out of the ordinary. I have until the end of the month before my payments are bricked :)

I should be getting something on the reader that tells me their is an optional update because my reader is 1 version behind, but the available update property on the active reader is null.

## Code to reproduce
```
Terminal.Instance.ConnectBluetoothReader(readerToPair, new BluetoothConnectionConfiguration(locationId), this, new ReaderConnectionCallback((connectedReader, ex) =>
                {
                    System.Diagnostics.Debug.WriteLine("**** ConnectBluetoothReader Callback *****");

                    if (ex != null)
                    {
                        System.Diagnostics.Debug.WriteLine(ex.Message + " " + ex.ErrorMessage);

                        onReaderConnectionSuccess(false);
                    }
                    else
                    {
                        _connectedReader = connectedReader;

                        onReaderConnectionSuccess(true);
                    }
                }));
```

## Android version
8.1.0

## Impacted devices (Android devices or readers)
BBPOS Chipper

## SDK version
2.5.2

## Other information
Resolved pending breakpoint at 'DiscoverReadersPageModel.cs:276,1' to void StubScannr.PageModels.DiscoverReadersPageModel.ScanTimeout () [0x00001].
Resolved pending breakpoint at 'DiscoverReadersPageModel.cs:278,1' to void StubScannr.PageModels.DiscoverReadersPageModel.ScanTimeout () [0x0001b].
[StripeTerminal] class=Terminal app_language=KOTLIN
[StripeTerminal] class=LocationHandler message=startListening
[StripeTerminal] class=ConnectionTokenManager message=refreshToken
Thread started:  #26
[StripeTerminal] class=TransactionStateMachine message="onStateChanged: null -> EMPTY: null"
[StripeTerminal] class=TransactionManager message="handleCardStatus NO_CARD"
[StripeTerminal] class=Terminal message=discoverReaders
[StripeTerminal] class=BbposAdapter message=discoverReaders
[ConnectionManager] startDiscovery
[StripeTerminal] class=TransactionStateMachine message="onStateChanged: EMPTY -> DISCOVER: Discovery requested"
[BBBTDiscoveryController] discoverDevices
[BluetoothAdapter] isLeEnabled(): ON
[BluetoothLeScanner] onScannerRegistered() - status=0 scannerId=8 mScannerId=0
[Choreographer] Skipped 66 frames!  The application may be doing too much work on its main thread.
[zygote64] Do partial code cache collection, code=247KB, data=206KB
[zygote64] After code cache collection, code=247KB, data=206KB
[zygote64] Increasing code cache capacity to 1024KB
[zygote64] Compiler allocated 4MB to compile void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int)
[zygote64] Compiler allocated 7MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
[StripeTerminal] class=ConnectionTokenManager message=fetchConnectionToken.onSuccess
[StripeTerminal] class=ApiClient message=discoverLocations
[StripeTerminal] class=RestClient message="url=https://api.stripe.com//v1/terminal/readers/discover request={"readers":["CHB204902000372"]}"
[RestResponse] REST response with code 200 received
[RestResponse] request-id: req_rhfj8KQpbByHFD
[StripeTerminal] class=RestClient message="url=https://api.stripe.com//v1/terminal/readers/discover status=OK headers={access-control-allow-credentials=true, access-control-allow-methods=GET, POST, HEAD, OPTIONS, DELETE, access-control-allow-origin=*, access-control-expose-headers=Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required, access-control-max-age=300, cache-control=no-cache, no-store, content-length=522, content-type=application/json, date=Tue, 07 Dec 2021 03:40:42 GMT, idempotency-key=1638848441461unknownodvGxKY3, original-request=req_rhfj8KQpbByHFD, request-id=req_rhfj8KQpbByHFD, server=nginx, strict-transport-security=max-age=31556926; includeSubDomains; preload, stripe-should-retry=false, stripe-version=2020-03-02} response={"readers":[{"location":{"address":{"city":"Rogers","country":"US","line1":"123 Test St","line2":"Suite 4","postalCode":"72758","state":"AR"},"displayName":"Stripe Terminal Addr Line 2","id":"tml_EajaVgIS3U9Qpl","livemode":false},"serialNumbers":["CHB204902000372"]}]}"
[StripeTerminal] class=ProxyDiscoveryListener message=onUpdateDiscoveredReaders([CHB204902000372])
Thread started:  #27
[StripeTerminal] class=Terminal message=connectBluetoothReader serial_number=CHB204902000372
[StripeTerminal] class=TransactionManager message=endTransaction
[ConnectionManager] endOperation
[UpdateManager] endOperation
[StripeTerminal] class=TransactionStateMachine message="onStateChanged: DISCOVER -> CANCELLED: null"
[BBBTDiscoveryController] stopDiscoverReaders
[BluetoothAdapter] isLeEnabled(): ON
[StripeTerminal] class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
Thread started:  #28
[0:] **** Discover Readers Callback *****
[StripeTerminal] class=BbposAdapter message=connectReader
[StripeTerminal] class=ProxyTerminalListener message=onConnectionStatusChange(CONNECTING)
[0:] *** OnConnectionStatusChange CONNECTING ***
[ConnectionManager] startConnect
[StripeTerminal] class=TransactionStateMachine message="onStateChanged: EMPTY -> CONNECT: Connect requested"
[BBPOSReaderConnectionController] connectBluetooth
[StripeTerminal] class=BBPOSDeviceControllerImpl message=connectBT
[BluetoothGatt] connect() - device: 2F:23:D3:14:E7:51, auto: false
[BluetoothGatt] registerApp()
[BluetoothGatt] registerApp() - UUID=4311e8f5-9f12-4cc6-9e96-64c48366be00
[BluetoothGatt] onClientRegistered() - status=0 clientIf=8
[BluetoothGatt] onClientConnectionState() - status=0 clientIf=8 device=2F:23:D3:14:E7:51
[BluetoothGatt] discoverServices() - device: 2F:23:D3:14:E7:51
[BluetoothGatt] onConnectionUpdated() - Device=2F:23:D3:14:E7:51 interval=6 latency=0 timeout=500 status=0
[BluetoothGatt] onSearchComplete() = Device=2F:23:D3:14:E7:51 Status=0
[BluetoothGatt] setCharacteristicNotification() - uuid: 0000ffa1-0000-1000-8000-00805f9b34fb enable: true
[BluetoothGatt] onConnectionUpdated() - Device=2F:23:D3:14:E7:51 interval=39 latency=0 timeout=500 status=0
[BluetoothGatt] requestConnectionPriority() - params: 1
[BluetoothGatt] onConnectionUpdated() - Device=2F:23:D3:14:E7:51 interval=12 latency=0 timeout=2000 status=0
[BluetoothGatt] configureMTU() - device: 2F:23:D3:14:E7:51 mtu: 132
[zygote64] Compiler allocated 7MB to compile int com.stripe.bbpos.bbdevice.aaa001zz.aaa007(java.lang.String, java.lang.String)
[BluetoothGatt] onConfigureMTU() - Device=2F:23:D3:14:E7:51 mtu=132 status=0
[StripeTerminal] class=BBPOSControllerListener message=onBTConnected
[StripeTerminal] class=BluetoothBondStateReceiver message=stopListening
[ConnectionManager] startReaderInfo
[StripeTerminal] class=TransactionStateMachine message="onStateChanged: CONNECT -> READER_INFO: null"
[BBPOSReaderInfoController] requestReaderInfo
[StripeTerminal] class=BBPOSDeviceControllerImpl message=getDeviceInfo
[zygote64] Compiler allocated 8MB to compile int com.stripe.bbpos.bbdevice.aaa001zz.aaa002(java.lang.String, java.lang.String)
[zygote64] Do full code cache collection, code=489KB, data=350KB
[zygote64] After code cache collection, code=461KB, data=291KB
[StripeTerminal] class=BBPOSControllerListener message="onReturnDeviceInfo {firmwareVersion=1.00.03.34, deviceSettingVersion=SZZZ_Generic_v45, uid=47003B000F50483841353820, trackKsn=300002000043720000BC, productID=4348423230, vendorID=535A5A5A, isSupportedTrack3=false, isSupportedTrack2=true, isSupportedTrack1=true, emvKsn=300003000043720000A7, batteryPercentage=83, pinKsn=30000100004372000004, terminalSettingVersion=SZZZ_Generic_v45, productId=4348423230, isCharging=false, isUsbConnected=false, bootloaderVersion=5.00.16.22, sdkVersion=3.21.2, 1.6.17, bID=CHB204902000372, batteryLevel=3.993, formatID=60, serialNumber=CHB204902000372, macKsn=30000400004372000001, isSupportedNfc=true, hardwareVersion=1.0.4}"
[StripeTerminal] class=BbposAdapter reader_software_version=1.00.03.34-SZZZ_Generic_v45-300001 reader_battery_level=0.83
[StripeTerminal] class=ProxyTerminalListener message=onConnectionStatusChange(CONNECTED)
[0:] *** OnConnectionStatusChange CONNECTED ***
[ConnectionManager] endOperation
[StripeTerminal] class=TransactionStateMachine message="onStateChanged: READER_INFO -> CANCELLED: null"
[BBBTDiscoveryController] stopDiscoverReaders
[StripeTerminal] class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
[StripeTerminal] class=ConnectionTokenManager message=refreshToken
[StripeTerminal] class=DirectResourceRepository message=activateReader
[StripeTerminal] class=ApiClient message=activateReader
[StripeTerminal] class=RestClient message="url=https://api.stripe.com/v1/terminal/connection_tokens/activate request={"deviceSerialNumber":"CHB204902000372","deviceType":"bbpos_chipper2x","posDeviceId":"8ff29ce8-3550-4caa-968d-fdc80e2d18a2","posDeviceInfo":{"appModel":{"appId":"com.stubs.StubsScannr","appVersion":"1.1.8"},"deviceClass":"POS","deviceUuid":"8ff29ce8-3550-4caa-968d-fdc80e2d18a2","hardwareModel":{"posInfo":{"description":"TC20"}},"hostHwVersion":"TC20","hostOsVersion":"8.1.0"},"posVersionInfo":{"clientType":"ANDROID_SDK","clientVersion":"2.5.2"},"reader":{"appModel":{"appId":"firmware-config-key","appVersion":"1.00.03.34-SZZZ_Generic_v45-300001"},"bbposBaseConfig":"SZZZ_Generic_v45","bbposFirmware":"1.00.03.34","bbposKeyProfile":"300001","deviceClass":"READER","deviceUuid":"CHB204902000372","hardwareModel":{"bbposHardware":"CHIPPER2X"},"hostHwVersion":"1.0.4"},"registerToLocation":"tml_EajaVgIS3U9Qpl","reportedReaderConfig":{"keyId":"300001"}}"
[StripeTerminal] class=ConnectionTokenManager message=fetchConnectionToken.onSuccess
[RestResponse] REST response with code 200 received
[RestResponse] request-id: req_vR8B1NyMN9gWlX
[StripeTerminal] class=RestClient message="url=https://api.stripe.com/v1/terminal/connection_tokens/activate status=OK headers={access-control-allow-credentials=true, access-control-allow-methods=GET, POST, HEAD, OPTIONS, DELETE, access-control-allow-origin=*, access-control-expose-headers=Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required, access-control-max-age=300, cache-control=no-cache, no-store, content-length=609, content-type=application/json, date=Tue, 07 Dec 2021 03:40:58 GMT, idempotency-key=1638848458625CHB204902000372M2PcBGFT, original-request=req_vR8B1NyMN9gWlX, request-id=req_vR8B1NyMN9gWlX, server=nginx, strict-transport-security=max-age=31556926; includeSubDomains; preload, stripe-should-retry=false, stripe-version=2019-02-19} response={"accountId":"acct_19rUzUJM7QGeoQlX","accountRef":{"storeId":"tml_EajaVgIS3U9Qpl"},"connectionContextId":"tcc_1K3uY2JM7QGeoQlXmqESdkVQ","livemode":false,"readerId":"tmr_EaubRgNwyR56ZK","__redacted_fields":["readerRpcSessionToken","sdkRpcSessionToken","stripeSessionToken"]}"
[StripeTerminal] class=TerminalSession reader_id=tmr_EaubRgNwyR56ZK
[StripeTerminal] class=BbposAdapter message=checkForUpdate
[UpdateManager] startCheckForUpdates
[StripeTerminal] class=TransactionStateMachine message="onStateChanged: EMPTY -> CHECK_FOR_UPDATE: Check for update requested"
[BBPOSReaderConfigurationUpdateController] readReaderSettings: 9F4E9F1A
[StripeTerminal] class=BBPOSDeviceControllerImpl message=readTerminalSetting
[StripeTerminal] class=BBPOSControllerListener message=onReturnReadTerminalSettingResult
[StripeTerminal] class=TerminalLifecycleObserver message=applicationDidReceiveMemoryWarning memoryLevel=80 memoryProfile=TRIM_MEMORY_COMPLETE appId=com.stubs.StubsScannr
[StripeTerminal] class=TerminalLifecycleObserver message=applicationDidEnterBackground appId=null
[StripeTerminal] class=LocationHandler message=stopListening
[zygote64] Explicit concurrent copying GC freed 3590(369KB) AllocSpace objects, 5(100KB) LOS objects, 51% free, 3MB/7MB, paused 148us total 65.284ms

**Comment by dhenry-stripe** [comment] 2021-12-07 14:30
@chris-oswald the logs indicate that the process is getting to the point of checking for whether or not an update exists before stopping. Can you try reproducing the issue with one of the example apps?

**Comment by chris-oswald** [comment] 2021-12-07 14:35
Can you tell me what 3rd party libs might be used during the update check? I suspect I'm missing a library in my binding and the exception isn't being thrown.

**Comment by dhenry-stripe** [comment] 2021-12-07 15:01
@chris-oswald I'd expect a missing dependency to throw a ClassNotFoundException or something similar. Having said that, I don't see anything used by the update process that isn't already used prior to this in discovery or connect. For your 1.x implementation - did you have updates working? The update process requires an app restart which stands out to me as something that might be problematic with Xamarin.

> Can you try reproducing the issue with one of the example apps?

The reason i'm asking this is to help narrow down the surface area. If the update succeeds on the example app, and then you can successfully connect using your implementation we know that the issue is associated with the update process. If you can't update with the example app, then there may be something up with your account/the device firmware/etc.

**Comment by chris-oswald** [comment] 2021-12-07 22:15
@dhenry-stripe , I really appreciate your insight and you looking at the dependencies.

I did have optional updates working in the 1.X app, but when I'd update the firmware or config it never restarted the app in the 1.X versions (it did actually install successfully). I have a Zebra Android 10 device to that I'll try too. If that doesn't work, I'll try to get that Java app deployed and see what happens.  Keep you posted...

**Comment by cgwhouse** [comment] 2021-12-08 01:02
Hey there @chris-oswald, I'm working on Xamarin bindings for 2.5.2 and have encountered (probably) the same issue - neither `onSuccess()` nor `onFailure()` fires for my `ConnectBluetoothReader` callback. All required and optional reader update workflows are behaving as expected when I use the simulated reader and the different `SimulatedReaderUpdate` configs, just not with the physical Chipper 2X. I can connect to the same Chipper via the sample app without issue. My logs stop almost exactly where yours do (my last line is ` [StripeTerminal] class=BBPOSControllerListener message=onReturnReadTerminalSettingResult`).

Also, just curious: what did you do to bind `wire-runtime-4.0.0-alpha.11`? The `.jar` that I downloaded from [here](https://search.maven.org/artifact/com.squareup.wire/wire-runtime/4.0.0-alpha.11/jar) didn't seem to satisfy the Java bindings generator, so I had to build the `.jar` from source.

**Comment by chris-oswald** [comment] 2021-12-08 14:17
@cgwhouse, I do get onFailure to for ConnectBluetoothReader to fire, but onSuccess never works.  onFailure will fire when the timeout elapses or I manually call the cancel.

@dhenry-stripe , I tried Android 10 and received the same behavior and logs. Next step is to try the Java demo version.

**Comment by cgwhouse** [comment] 2021-12-08 14:25
> onFailure will fire when the timeout elapses or I manually call the cancel.

Which cancel are you referring to exactly? [ConnectBluetoothReader doesn't return a `Cancelable`](https://stripe.dev/stripe-terminal-android/core/core/com.stripe.stripeterminal/-terminal/index.html#242129535%2FFunctions%2F-1814817128).

**Comment by chris-oswald** [comment] 2021-12-08 16:05
@cgwhouse , you are totally right! I was thinking of DiscoverReaders... onFailure is called when I turn off the reader after it's connected. It's is firing for me, I just confused the event triggering it :)

**Comment by cgwhouse** [comment] 2021-12-08 22:28
Just wanted to follow up after more testing and debugging today - I'm seeing the same issue described above when trying to bind SDK versions `2.5.2`, `2.5.1`, and `2.4.1`. The last version of Stripe Terminal that I have confirmed working on Xamarin Android (using our own bindings, maintained internally) is `2.3.1`.

Something internal with the reader connection + "silent check for update while connecting" workflow seems to changed since `2.3.1` and upset Xamarin, physical devices only. Comparing our Xamarin app's logs to the sample app's, the next class that our Xamarin app should see logs from (but doesn't) is `CrpcClient`. Wondering what's doing the heavy lifting in that class?

 I'm not even seeing anything useful or actionable in the Logcat, which is typically not the case with these bindings... usually, if something is missing or bound incorrectly, you would see a runtime exception in the logs.

Hopefully this context is useful, to Stripe folks or anyone else!

**Comment by chris-oswald** [comment] 2021-12-08 23:03
@cgwhouse , that's incredibly helpful! At least I know I can move a few versions back and get something working. I wonder what Xamarin is upset about in these new versions. Hopefully @dhenry-stripe will be able to shed some light on CrpcClient.

**Comment by dhenry-stripe** [comment] 2021-12-08 23:42
Xamarin developers unite! Great that you've been able to help each other out. Perhaps the following will help:

> [StripeTerminal] class=BBPOSControllerListener message=onReturnReadTerminalSettingResult
A few things occur in between this log line and usages of `CrpcClient`. I'm assuming when it works you see logs from `CrpcClient` indicating that configs are being downloaded. `CrpcClient` uses a shaded version of okhttp so shouldn't be impacted by Xamarin.

`2.4.0` included a BBPOS SDK update. The BBPOS SDK doesn't include transitive dependencies, so I don't see how it could result in the kind of issue you're seeing. Interesting coincidence though.

Have either of you tried updating the reader using <= `2.3.1`, and then attempted to connect to the successfully updated reader using > `2.3.1`? Do you see the same behavior? The outcome of this will help to narrow down how far through the update process it's getting.

**Comment by chris-oswald** [comment] 2021-12-08 23:46
@dhenry-stripe , I will try to get 2.3.1 working tonight now that I know to shoot for a specific version. keep you posted unless @cgwhouse beats me to it.

**Comment by cgwhouse** [comment] 2021-12-09 15:50
When I connect to my Chipper using `2.3.1`, it connects successfully and returns a software version of `1.00.03.34.921a53dc-SZZZ_Generic_v46-300001`. I don't know whether it actually performs an update or not, but based on my understanding of how the 2.x SDK works, since it connects successfully and reports no optional updates --> I'm assuming it's updated.

When I then try to connect to the same reader using > `2.3.1`, I get the halting behavior at the `onReturnReadTerminalSettingResult` log entry. My suspicion is that it's failing to even check for an update now, if my previous assumption is correct (that this device is already up to date). And that update check relies on okhttp, am I getting all of that right?

**Comment by dhenry-stripe** [comment] 2021-12-09 16:13
Thanks @cgwhouse, yes it does sound like its failing prior to the start of the update.

> And that update check relies on okhttp, am I getting all of that right?

That's correct, but okhttp is used prior to this as well so I don't think it's the cause. 

Can you please add the following meta tag to your manifest? This will enable BBPOS SDK debug logging. 

```
<meta-data
    android:name="com.stripe.stripeterminal.enable_reader_logging"
    android:value="true" />
```
After enabling it, can you please post the `readTerminalSetting` and `onReturnReadTerminalSettingResult` output from BBPOS? It looks something like this:

```
D/com.bbpos: [BBDeviceController] [readTerminalSetting] dol : [some value]
29728-30102/com.stripe.terminal.testapp D/com.bbpos: [BBDeviceController] [onReturnReadTerminalSettingResult] data : [some value]
```

**Comment by chris-oswald** [comment] 2021-12-09 16:47
@dhenry-stripe , I added this to my manifest `<meta-data android:name="com.stripe.stripeterminal.enable_reader_logging" android:value="true" />`

I never saw the line output in my log file after adding it to my manifest. @cgwhouse , I'll be curious on your results.

**Comment by cgwhouse** [comment] 2021-12-09 16:54
@chris-oswald I had to add it to the `<application>` to produce the new logs; it seemingly didn't work to just add it at the `<activity>` level. Hope that helps.

@dhenry-stripe , here's what I've got:

```
D/com.stripe.bbpos: [BBDeviceController] [readTerminalSetting] dol : 9F4E9F1A
D/com.stripe.bbpos: [BBDeviceController] [onReturnReadTerminalSettingResult] data : {9F4E=6A8E9E827F744BBD7F10EF4F7E0418ED, 9F1A=0840}
```

**Comment by dhenry-stripe** [comment] 2021-12-09 18:32
Thanks again, both of those values appear to be valid. Let's try something else, can you please post the serial number of the devices you're trying to connect to, along with the package id of your POS app?

**Comment by cgwhouse** [comment] 2021-12-09 18:52
Sure thing:

serial - `CHB202920000377`
package id - `com.blackbaud.mobilepay`

**Comment by dhenry-stripe** [comment] 2021-12-09 19:33
@cgwhouse I don't see any logs for that serial / packageId combination for 2.5.2. That tells me that the SDK isn't sending logs to our internal systems when the error occurs but gives me no visibility as to why. Can you confirm that you have bindings for all of the dependencies listed in the Terminal SDK poms?

https://repo1.maven.org/maven2/com/stripe/stripeterminal-internal-models/2.5.2/stripeterminal-internal-models-2.5.2.pom
https://repo1.maven.org/maven2/com/stripe/stripeterminal-external/2.5.2/stripeterminal-external-2.5.2.pom
https://repo1.maven.org/maven2/com/stripe/stripeterminal-internal-common/2.5.2/stripeterminal-internal-common-2.5.2.pom
https://repo1.maven.org/maven2/com/stripe/stripeterminal/2.5.2/stripeterminal-2.5.2.pom
https://repo1.maven.org/maven2/com/stripe/stripeterminal-core/2.5.2/stripeterminal-core-2.5.2.pom

**Comment by cgwhouse** [comment] 2021-12-09 20:21
Yep, those `.pom` files are my starting place when building these bindings. I'm able to bind everything for the most part, but there were a few that were a bit more difficult to deal with. I don't know how helpful this will be, but I'll list the more problematic ones and you tell me if it helps:

- `wire-runtime-4.0.0-alpha.11.jar` (the jar I initially used is linked in one of my earlier posts) only seemed to contain Kotlin metadata when downloaded from Maven, so I built alpha 11 from [source](https://github.com/square/wire) and included that instead
- AndroidX.Annotations doesn't have bindings for `1.3.0` on NuGet yet, so we're using `1.2.0`
- Guava doesn't have bindings for `28.1` on NuGet, so we're using `28.2`
- Gson doesn't seem to be included in any `.pom` files, but the SDK complains without it - so we're arbitrarily using `2.8.9`
- Including Conscrypt `2.5.2` seems to prevent some exceptions from appearing in the application logs, but whether it's included or not doesn't seem to affect any actual SDK functionality

I think those are all of our "discrepancies", if you will... everything else is incorporated in the standard way, either by downloading an official NuGet package containing bindings from Microsoft, or embedding the jars/aars directly.

**Comment by cgwhouse** [comment] 2021-12-09 21:34
@dhenry-stripe I think you're onto something. We are "manually" loading in okio 2.60 via NuGet package to satisfy okhttp `4.7.2`. I don't believe okio `3.0.0-alpha.9` is currently included anywhere in our bindings. I will also update the gson version to be sure that isn't the issue.

Dumb question that may have more to do with differences in package ecosystems than anything else: can I just swap okio `2.6.0` for `3.0.0-alpha.9`, or do I need to somehow make it so that both are available?

**Comment by cgwhouse** [comment] 2021-12-09 22:01
That seems to have done it! Ensuring `3.0.0-alpha.9` is the only okio was the fix. I will keep smoke testing the SDK to ensure we don't run into any other issues.

@chris-oswald , make sure your bindings don't use the Square.Moshi, Square.Moshi.Adapters, or Square.OkIO NuGet packages. These will all pull in okio `2.x` which apparently is the root cause of the issue.

**Comment by cgwhouse** [comment] 2021-12-09 22:04
@dhenry-stripe , thank you so much for your help. Help me understand something: the `.pom` file available [here](https://search.maven.org/artifact/com.squareup.wire/wire-runtime/4.0.0-alpha.11/jar) doesn't list okio as a dependency. Could this be a bug in that version of Square's library, similar to the missing Gson dependency?

**Comment by dhenry-stripe** [comment] 2021-12-09 22:11
> can I just swap okio 2.6.0 for 3.0.0-alpha.9, or do I need to somehow make it so that both are available?

Swapping 2.6.0 for 3.0.0-alpha.9 is the way to go. If you load both I imagine you'd see a `DuplicateClassFoundException`.

> That seems to have done it! Ensuring 3.0.0-alpha.9 is the only okio was the fix. I will keep smoke testing the SDK to ensure we don't run into any other issues.

That's great news!

> Help me understand something: the .pom file available here doesn't list okio as a dependency. Could this be a bug in that version of Square's library, similar to the missing Gson dependency?

It sure looks that way. The 4.0.0 [.pom](https://search.maven.org/artifact/com.squareup.wire/wire-runtime/4.0.0/jar) for wire-runtime *does* include okio.

**Comment by cgwhouse** [comment] 2021-12-09 23:10
Hmm, this is technically off-topic now, but for whatever reason I'm seeing an exception with message "You must request Bluetooth permissions before initializing the Terminal" when trying to initialize the `2.5.2` SDK on an Android 12 emulator. I thought this was resolved with [issue 171](https://github.com/stripe/stripe-terminal-android/issues/171) and SDK version `2.4.1`. Is this expected behavior / do we need to request this from the user?

**Comment by dhenry-stripe** [comment] 2021-12-09 23:19
This is expected behavior. Android 12 added new bluetooth permissions that need to be requested. The issue you linked resolved an issue where BBPOS SDK didn't understand the new permissions. 

More details here (note the api level specific permissions checks): https://github.com/stripe/stripe-terminal-android/blob/master/Example/kotlinapp/src/main/java/com/stripe/example/MainActivity.kt#L76

**Comment by cgwhouse** [comment] 2021-12-10 01:18
Understood, I misread the issue originally - thanks so much again @dhenry-stripe!

**Comment by chris-oswald** [comment] 2021-12-10 13:22
@cgwhouse  @dhenry-stripe , I finally got the reader connection working. Thank you both for all your help!

@cgwhouse , I wouldn't have gotten there as quickly without your insights into the bindings - I really appreciate it!

**Closed** 2021-12-10 15:16 UTC

**Comment by dhenry-stripe** [comment] 2022-01-25 00:44
Gson included as explicit dependency in [v2.6.0](https://github.com/stripe/stripe-terminal-android/releases/tag/v2.6.0).

**Comment by leoslima13** [comment] 2022-02-04 13:46
Hey @chris-oswald.
I saw that you already have a version binding to 1.x and it's working.
I'm facing the same problem as you on version 2.x, my ReaderCallback never reaches, I mean the OnSuccess method is never called, but if something gets wrong or if I try to invoke another command at the same time, the OnFailure is called.
I'm using the version 1.0.18 (aar file) and followed the .pom archive from MVN repository to create the dependencies, but i got stuck, can you help me with the version that you have? Maybe sharing it with me.
And I can't upgrade it to version 2.x yet, because we don't have the structure prepared to migrate for location things (required by version 2.x from sdk) and also because we have a version for iOS in production using 1.x

**Comment by chris-oswald** [comment] 2022-04-30 16:09
@leoslima13 , sorry for not seeing this sooner, did you figure it out?
