### ISSUE TITLE
WP3 Tipping configuration does not update unless restarted

### ISSUE THREAD

**Issue by yogen-p** [stripe/stripe-terminal-android#227] opened 2022-04-22 08:38 UTC
## Summary
After updating the tipping config from the app, and reconnecting to the reader, the tipping config does not update and the reader still shows the old one. I guess there's some sort of caching in the SDK.
It works fine if I restart the app and works fine on iOS as well.
This is also an issue because we've got this scenario where a user can have multiple merchants. So, even if I use different location IDs, we have a different one for every merchant, it still picks up the old config and doesn't update at all.

## Code to reproduce
Change tipping config in the same session of the app, and try taking a payment.

## Android version
12

## Impacted devices (Android devices or readers)
Pixel 3 XL

## SDK version
2.8.1

**Comment by sjl-stripe** [comment] 2022-04-22 21:40
Hi @yogen-p, thanks for reporting this issue.

I was unable to reproduce this issue with Android SDK 2.8.1 and the [Terminal Example App](https://github.com/stripe/stripe-terminal-android/tree/master/Example/kotlinapp). Here are the steps I used in an attempt to reproduce this issue:
1. Set tipping configs on account. (e.g. percentage tipping with 15%, 20%, 25%)
2. Call `connectBluetoothReader` to connect WisePad 3
3. Collect payment. verify that the tip selection screen shows 15%, 20%, 25%
4. Update tipping configs with new values. (e.g. percentage tipping with 16%, 21%, 26%)
5. Call `disconnectReader` and then `connectBluetoothReader`
6. Collect payment. verify that the tip selection screen shows 16%, 21%, 26%


The issue might have been caused by poor network connectivity or a transient network issue. Could you try connecting your WisePad 3 to your Android POS app where you have a stronger WIFI signal? If that doesn't work, please provide the following information so we can troubleshoot further:
* Logs from your POS app if possible
* WisePad 3 reader serial number used to reproduce this issue (e.g. WPC3230270000325 - can be found at the back of your WisePad 3 reader)
* Approximately when you reproduced this issue (e.g. 10AM BST on April 22)

It's possible that the issue you're reporting isn't caused by a transient network issue. It could be an integration issue where the POS app isn't disconnecting and reconnecting the WisePad 3 reader properly. Logs will help us confirm if that's the case.

**Comment by nisd93** [comment] 2022-04-26 07:46
@yogen-p Does this collect on reader tips working for you? https://stripe.com/docs/terminal/features/collecting-tips/on-reader
Can you provide more details?

**Comment by yogen-p** [comment] 2022-04-26 09:05
Hey @nisd93 @sjl-stripe Thanks for your response, and sorry for the delay. We were waiting for the 2.9.0 release as it had a crash fix and hence tipping was on hold. I'll provide more info with more logs in a bit.

**Comment by nisd93** [comment] 2022-04-26 09:48
@yogen-p They have just released 2.9.0 today, check please!!

**Comment by yogen-p** [comment] 2022-04-27 12:21
Hey, I've got some logs for you. The issue is that I can't exactly pinpoint why and when this happens because it was working fine for a while and then suddenly it freaked out when I switch from fixed amount to percentages. I can't say that this is when it always happens. On top of this, as I mentioned earlier that we have a scenario where one user can have multiple merchants which means multiple `stripeLocationIds` and in this case I can always replicate the issue.

Also, I'm using the latest SDK 2.9.0

Terminal Serial: **WPC323105000820**

All transactions done on **27 April 2022**, with a good connectivity of **100+Mbps.**

- First payment logs with initial tipping config:
Around 13:01:47 BST
```
class=TransactionStateMachine message="onStateChanged: EMPTY -> TIPPING_SELECTION: Tipping selection requested"
class=TransactionStateHandler message="Processing fixed amount tip"
class=TransactionStateHandler message="Tip config result: FixedAmountTips(currency=GBP, stringAmount=5.00, amountTips=[2.50, 9.99, 1.99])"

Test Payment intent: pi_3Kt9Z1KHV9I0GxFc09PFlKde
```

- Second payment logs with updated tipping config:
For this transaction the config should’ve been percentages [11,21,31]
Around 13:02:33 BST
```
class=TransactionStateMachine message="onStateChanged: EMPTY -> TIPPING_SELECTION: Tipping selection requested"
class=TransactionStateHandler message="Processing fixed amount tip"
class=TransactionStateHandler message="Tip config result: FixedAmountTips(currency=GBP, stringAmount=5.00, amountTips=[2.50, 9.99, 1.99])"

Test Payment intent: pi_3Kt9ZlKHV9I0GxFc0iMtO51f
```

- For the third transaction, before which I went into app settings and selected “Clear cache”:
Around 13:06:59 BST.
It works as expected.
```
class=TransactionStateMachine message="onStateChanged: EMPTY -> TIPPING_SELECTION: Tipping selection requested"
class=TransactionStateHandler message="Processing fixed percentage tip"
class=TransactionStateHandler message="Tip config result: PercentageTips(currency=GBP, stringAmount=10.00, percentageTips=[11, 21, 31])"

Test Payment intent: pi_3Kt9e3KHV9I0GxFc1Q1OiNeF
```

**Comment by sjl-stripe** [comment] 2022-04-29 21:55
@yogen-p  - thanks for the logs and timestamps. 

You're seeing stale tipping configs because our backend caches the [Location](https://stripe.com/docs/api/terminal/locations) object. Here's why you got stale configs:

* On 13:01:33 BST - the Android SDK fetches the tipping config right after you connect your WP3 reader to your POS app. Our backend gets tipping configs from a configuration override set to a [`Location`](https://stripe.com/docs/api/terminal/locations). The `Location` object is cached in our backend for a minute.
* On 13:02:17 BST - you create a new [`Configuration`](https://stripe.com/docs/api/terminal/configuration/object?Do=) object with percentage tipping configs. 
* On 13:02:19 BST - you set the `configuration_override` for your `Location` with the new `Configuration`.
* On 13:02:27 BST - the Android SDK fetches tipping config again but our backend sends stale tipping configs. This is because our backend caches the `Location`  object for a minute. The `configuration_override` for the `Location` is stale so stale tipping configs are sent.

Can you try updating the Configuration object instead of creating a new one?  See our API documentation for [updating a Configuration](https://stripe.com/docs/api/terminal/configuration/update). If you are currently creating a new configuration object for a single use, updating an existing configuration is preferred so there aren't a bunch of unused configuration objects lying around.

Also, can you elaborate on the use case as to why you're using custom/different tipping configs immediately before each transaction? The backend configurations are meant to be a bit more static (hence, why we cache them for improved performance), but we'd like to better understand your use case.

Finally, I know you mentioned that you aren't seeing this problem on iOS, but we believe that's just a coincidence. The caching that you are running into happens in the backend and should affect Android and iOS the same. The only subtle difference may be that the Android SDK may be connecting to the reader more quickly, so it may be more likely to retrieve the cached version of the `Location`.

**Comment by billfinn-stripe** [comment] 2022-05-19 17:24
@yogen-p -- just checking in here to confirm you're seeing behavior that aligns with what @sjl-stripe described. Does the current eventually consistent behavior work for you? If so, would you be ok closing this issue? If not, can you elaborate on your use case?

**Comment by billfinn-stripe** [comment] 2022-05-24 19:21
@yogen-p -- I'm going to close this PR, assuming that our previous responses have led you to a solution. Please feel free to reopen if you are still encountering problems. Thanks!

**Closed by billfinn-stripe** 2022-05-24 19:21 UTC

**Comment by yogen-p** [comment] 2022-05-26 10:02
Hi guys, I completely missed this as we got busy with other tickets and no merchant has complained about this yet.
But, the issue is still happening and I can replicate it all the time. However, I have noticed that this can be replicated every time if I'm trying to update the values for the same type
Eg: If my original config was of Percentages type as 10, 12, 15 and I update values to say 10, 14, 15 then it doesn't update. If I switch types say going from Percentages 10, 12, 15 to Fixed values £2.50, £5.00, £7.50 it works as expected.

A workaround that seems to work is going into App info and selecting "Clear cache" and this confirms that it is a caching issue.

I understand from our data merchants don't update config so often to experience this but updating values for the same type, I believe, is a pretty common use case and should be fixed.

Let me know if you need any logs or other information from me. Thanks.

**Comment by billfinn-stripe** [comment] 2022-05-26 14:31
Hi @yogen-p -- can you clarify as to the steps you are taking to replicate the issue? Specifically, if you update the config, wait for ~5 minutes, and then connect to the reader, are you still seeing this issue?

I can't explain why updating the config of the same type would be any different from changing types, so I'm curious to learn more.

If you're able to reproduce after waiting ~5 minutes for our backend caches to clear, can you send a timeline, the reader serial number you're using for testing, and any of the configuration IDs that you are creating/modifying while trying to reproduce?

**Comment by yogen-p** [comment] 2022-05-27 12:24
@billfinn-stripe It's all a bit weird but I've got a very specific scenario that might help.
- I had tipping config set as amounts: £1.00, £1.50, £3.00
- I updated the tipping config as percentages 10, 12, 15.
- As you said about your caching and everything the config didn't update and the reader said amounts: £1.00, £1.50, £3.00.

Now the weird thing is this all happened yesterday. And I'm still seeing amounts: £1.00, £1.50, £3.00 on the reader for some reason. I can't say that the issue is always replicable when changing values as compared to when changing types. It happens in every possible scenario but the frequency varies. 

Also, whenever I update the config it's not possible to wait for 5 minutes before reconnecting, I need to do it straight away.

Reader ID: `WPC323105000820`
Request ID(If it helps): `req_qeAzzKIjGo02c8`

I can create some videos and snaps with logs for you to review if it helps and upload it in a drive.

**Comment by billfinn-stripe** [comment] 2022-05-27 16:32
@yogen-p -- great, thanks. To clarify, if your reader is using configuration A, you create a new configuration B, update your location to use configuration B, and then immediately reconnect to the reader, the expected behavior is that the reader may use the *old* configuration A still. We cache the location in the backend for performance reasons.

Can you elaborate on the use case where users are updating the tip amounts ~regularly?

**Comment by yogen-p** [comment] 2022-05-27 16:41
Honestly speaking, we don't expect merchants to update their config too often and as I said we haven't heard any complaints yet either. But it's just something that is not a good UX and somewhere down the line more people might start to experience it.
