### ISSUE TITLE
Issue connecting to reader

### ISSUE THREAD

**Issue by thelight413** [stripe/stripe-terminal-android#477] opened 2024-07-25 22:25 UTC
## Summary
I'm getting an error when trying to discover readers whether it's NFC or an M2 reader.
The error I'm getting is 
<img width="1128" alt="Screenshot 2024-07-25 at 6 22 45 PM" src="https://github.com/user-attachments/assets/25dd0493-c5b3-439e-9522-b56273482951">

## Code to reproduce
````
public void discoverReaders(String method, int simulated, int timeout) {
        boolean isSimulated = isApplicationDebuggable();
        try {
            DiscoveryConfiguration discoveryConfiguration = null;
//            discMethod = DiscoveryMethod.valueOf(DiscoveryMethod.BLUETOOTH_SCAN.);
// Our only discovery method for Android
            if (method.equals("internet")) {
//                discoveryConfiguration = new DiscoveryConfiguration.InternetDiscoveryConfiguration(location,isSimulated);
            } else if (method.equals("local")) {
                isSimulated = isApplicationDebuggable();
                discoveryConfiguration = new DiscoveryConfiguration.LocalMobileDiscoveryConfiguration(isSimulated);
            } else if (method.equals("embedded")) {
            } else if (method.equals("handoff")) {
                discoveryConfiguration = new DiscoveryConfiguration.HandoffDiscoveryConfiguration();

            } else if (method.equals("usb")) {
                discoveryConfiguration = new DiscoveryConfiguration.BluetoothDiscoveryConfiguration(timeout, isSimulated);
            } else {
                discoveryConfiguration = new DiscoveryConfiguration.BluetoothDiscoveryConfiguration(timeout, isSimulated);

            }
//            DiscoveryConfiguration discoveryConfiguration = new DiscoveryConfiguration(timeout, discMethod, isSimulated);
            Callback statusCallback = new Callback() {
                @Override
                public void onSuccess() {
                    pendingDiscoverReaders = null;
                    WritableMap readerCompletionResponse = Arguments.createMap();
                    sendEventWithName(EVENT_READER_DISCOVERY_COMPLETION, readerCompletionResponse);
                }

                @Override
                public void onFailure(@Nonnull TerminalException e) {
                    pendingDiscoverReaders = null;
                    WritableMap errorMap = Arguments.createMap();
                    errorMap.putString(ERROR, e.getErrorMessage());
                    sendEventWithName(EVENT_READER_DISCOVERY_COMPLETION, errorMap);
                }
            };

            abortDiscoverReaders();
            if (ActivityCompat.checkSelfPermission(getContext().getApplicationContext(), Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(getContext().getApplicationContext(), Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
                // TODO: Consider calling
                //    ActivityCompat#requestPermissions
                // here to request the missing permissions, and then overriding
                //   public void onRequestPermissionsResult(int requestCode, String[] permissions,
                //                                          int[] grantResults)
                // to handle the case where the user grants the permission. See the documentation
                // for ActivityCompat#requestPermissions for more details.
                return;
            }
            assert discoveryConfiguration != null;
            pendingDiscoverReaders = Terminal.getInstance().discoverReaders(discoveryConfiguration, this, statusCallback);

        } catch (Exception e) {
            e.printStackTrace();

            if (e.getMessage() != null) {
                WritableMap writableMap = Arguments.createMap();
                writableMap.putString(ERROR, e.getMessage());
                sendEventWithName(EVENT_READER_DISCOVERY_COMPLETION, writableMap);
            }
        }
    }
``````

## Android version
Android 14

## Impacted devices (Android devices or readers)
Pixel 6, M2 reader or NFC reader
## SDK version
3.7.1

**Comment by ugochukwu-stripe** [comment] 2024-07-26 15:45
@thelight413 the logs above are a warning from the SDK's failed attempt to fetch cached locations; it does not fail the discovery operation. The log immediately afterwards `onUpdateDiscoveredReaders` confirms the sdk returns an empty list of readers to your application. Please see details [^1] for using your M2 reader, and let us know if you're having issues with discovery.

[^1]: https://docs.stripe.com/terminal/payments/setup-reader/stripe-m2

**Comment by thelight413** [comment] 2024-07-26 20:22
I got it to discover the reader but it stays on the status "connecting" for a while and then just disconnects.
The error I get is "timed out waiting for connection token".
<img width="1088" alt="Screenshot 2024-07-26 at 4 18 52 PM" src="https://github.com/user-attachments/assets/86b537f7-6d40-494a-8e81-6b37b7e37a2d">

<img width="1187" alt="Screenshot 2024-07-26 at 4 20 19 PM" src="https://github.com/user-attachments/assets/3dd371be-dc39-4538-a61c-5d76a8c83315">

**Comment by thelight413** [comment] 2024-07-26 21:33
Just to add just in case this helps. It seems like connection token is being refreshed twice. once during initialization and once during forwarding offline payments. Its refreshing one after the other.

<img width="1054" alt="Screenshot 2024-07-26 at 5 25 00 PM" src="https://github.com/user-attachments/assets/b262d52a-d7af-453f-b751-41912770e50f">

**Comment by ugochukwu-stripe** [comment] 2024-07-29 21:33
`Terminal` requires a connection token [^1] to activate your session so the reader can take payments, it seems your application is not providing a `ConnectionToken` hence the error. I'd suggest trying the example application [^2] if you haven't already to resolve integration errors in your application. Closing this out since it is an integration issue, feel free to open a new issue if you find bugs with the library.

[^2]: https://github.com/stripe/stripe-terminal-android?tab=readme-ov-file#configure-your-app
[^1]: https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.callable/-connection-token-provider/index.html

**Closed by ugochukwu-stripe** 2024-07-29 21:33 UTC

**Comment by thelight413** [comment] 2024-08-15 22:08
I'm still having this issue. When you run the app for the first time, do an initialization, discover readers and trying to connecting to a reader it will not connect to the reader because it doesn't **attempt** at getting the connection token. I put logs before and after it gets a connection token and it doesn't try getting the connection token on a fresh install. But if I swipe out of the app and run the app again it does get the connection

**Comment by ugochukwu-stripe** [comment] 2024-08-15 23:19
Can you reproduce with example application [^1]? 
[^1]: https://github.com/stripe/stripe-terminal-android?tab=readme-ov-file#try-the-example-app
