### ISSUE TITLE
SimulatedBbposAdapter.java:18: Caused by: java.lang.IllegalArgumentException: Unknown pattern character 'Y'.

### ISSUE THREAD

**Issue by gstcyr** [stripe/stripe-terminal-android#16] opened 2019-03-14 17:04 UTC
Getting this error on a device running Android 5.1.1 (API Level 22) since support for the capital Y in SimpleDateFormat was only added in API Level 24. 
Any chance we could replace the capital Y with a small 'y'?

**Comment by danwaters-stripe** [comment] 2019-03-14 18:21
Thanks for reporting. We'll make sure to get a fix in for this issue in our next release.

**Comment by SharathKaribasappaGB** [comment] 2019-04-08 04:07
I have also observed this issue and app is crashing due to this
stack traces
------
Caused by java.lang.IllegalArgumentException: Unknown pattern character 'Y'
       at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
       at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:298)
       at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
       at com.stripe.stripeterminal.SimulatedBbposAdapter.<clinit>(SimulatedBbposAdapter.java:18)
       at com.stripe.stripeterminal.TerminalModule.provideSimulatedAdapter(TerminalModule.java:108)
       at com.stripe.stripeterminal.TerminalModule_ProvideSimulatedAdapterFactory.proxyProvideSimulatedAdapter(TerminalModule_ProvideSimulatedAdapterFactory.java:48)
       at com.stripe.stripeterminal.TerminalModule_ProvideSimulatedAdapterFactory.provideInstance(TerminalModule_ProvideSimulatedAdapterFactory.java:34)
       at com.stripe.stripeterminal.TerminalModule_ProvideSimulatedAdapterFactory.get(TerminalModule_ProvideSimulatedAdapterFactory.java:27)
       at com.stripe.stripeterminal.TerminalModule_ProvideSimulatedAdapterFactory.get(TerminalModule_ProvideSimulatedAdapterFactory.java:8)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.stripe.stripeterminal.TerminalModule_ProvideMasterAdapterFactory.provideInstance(TerminalModule_ProvideMasterAdapterFactory.java:34)
       at com.stripe.stripeterminal.TerminalModule_ProvideMasterAdapterFactory.get(TerminalModule_ProvideMasterAdapterFactory.java:26)
       at com.stripe.stripeterminal.TerminalModule_ProvideMasterAdapterFactory.get(TerminalModule_ProvideMasterAdapterFactory.java:8)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.stripe.stripeterminal.TerminalModule_ProvideTerminalSessionFactory.provideInstance(TerminalModule_ProvideTerminalSessionFactory.java:57)
       at com.stripe.stripeterminal.TerminalModule_ProvideTerminalSessionFactory.get(TerminalModule_ProvideTerminalSessionFactory.java:39)
       at com.stripe.stripeterminal.TerminalModule_ProvideTerminalSessionFactory.get(TerminalModule_ProvideTerminalSessionFactory.java:8)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.stripe.stripeterminal.TerminalModule_ProvideTraceFactoryFactory.provideInstance(TerminalModule_ProvideTraceFactoryFactory.java:33)
       at com.stripe.stripeterminal.TerminalModule_ProvideTraceFactoryFactory.get(TerminalModule_ProvideTraceFactoryFactory.java:26)
       at com.stripe.stripeterminal.TerminalModule_ProvideTraceFactoryFactory.get(TerminalModule_ProvideTraceFactoryFactory.java:8)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.stripe.stripeterminal.DaggerTerminalComponent.getTraceFactory(DaggerTerminalComponent.java:173)
       at com.stripe.stripeterminal.Terminal.initTerminal(Terminal.java:57)
       at com.genbook.android.manager.stripeterminal.StripeTerminalManager.initStripeTerminal(StripeTerminalManager.java:138)
       at com.genbook.android.manager.screens.checkout.helpers.CheckoutPayments.initReader(CheckoutPayments.java:118)
       at com.genbook.android.manager.screens.checkout.main.CheckoutMainView.checkPermissions(CheckoutMainView.java:874)
       at com.genbook.android.manager.screens.checkout.main.CheckoutMainView.onViewResume(CheckoutMainView.java:195)
       at com.genbook.android.base.base.ViewManagerDelegate.show(ViewManagerDelegate.java:91)
       at com.genbook.android.base.flow.Router.show(Router.java:80)
       at com.genbook.android.base.flow.Router.add(Router.java:76)
       at com.genbook.android.base.flow.BaseViewManager.addOrShowNewController(BaseViewManager.java:156)
       at com.genbook.android.base.flow.ViewManager.goForwardInternal(ViewManager.java:158)
       at com.genbook.android.base.flow.ViewManager.lambda$goForward$0$ViewManager(ViewManager.java:26)
       at com.genbook.android.base.flow.ViewManager$$Lambda$0.run(Unknown Source)
       at com.genbook.android.manager.helpers.ActivityHelperImpl.runOnUiThread(ActivityHelperImpl.java:55)
       at com.genbook.android.base.flow.ViewManager.goForward(ViewManager.java:25)
       at com.genbook.android.base.flow.Flow.goForward(Flow.java:138)
       at com.genbook.android.base.flow.Flow$Builder.goForward(Flow.java:127)
------

**Comment by danwaters-stripe** [comment] 2019-04-19 21:07
This issue has been fixed in v1.0.0-b2.

**Closed by danwaters-stripe** 2019-04-19 21:07 UTC
