### ISSUE TITLE
Connection to the reader hangs and the SDK claims reader is connected

### ISSUE THREAD

**Issue by Milszym** [stripe/stripe-terminal-android#138] opened 2021-06-22 10:20 UTC
## Summary
I am encountering an issue when connecting to the WisePad 3 reader after the discovery process. It seems like sometimes nothing happens when Stripe Android SDK is requested to connect to the discovered reader. Most of the attempts work properly, but usually, about 1/10 attempts are not reacting to the request.

The connection request does not result in neither success nor failure in the specified `ReaderCallback`. I have been trying to wait 10 minutes for the connection, but there were no events, while the connection usually takes just a few seconds.
What's more, Stripe Android SDK claims that the reader is connected. If I call `Terminal.getInstance().connectedReader`, it returns the reader I requested it to connect with. But when I try to do anything with it, e.g. pay or disconnect, it "hangs" as well (meaning it does not result in neither success nor failure).
When this issue occurs, the only way to re-connect the reader correctly is "force closing" the app and clearing its cache and storage. As a result, Stripe SDK stops claiming the terminal device is connected and I can try to connect again.

Here are some logs produced by Stripe Android SDK when the connection is successful:

```
2021-06-22 10:42:21.731 18302-20903/my.package D/StripeTerminal: class=Terminal message=discoverReaders
2021-06-22 10:42:21.743 18302-26104/my.package D/StripeTerminal: class=BbposAdapter message=discoverReaders
2021-06-22 10:42:21.750 18302-26104/my.package I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: EMPTY -> DISCOVER: Discovery requested"
2021-06-22 10:42:24.945 18302-26102/my.package D/StripeTerminal: class=ApiClient message=discoverLocations
2021-06-22 10:42:25.394 18302-26102/my.package I/StripeTerminal: class=RestClient message="url=https://api.stripe.com//v1/terminal/readers/discover request={"readers":["WPC3230*******"]}"
2021-06-22 10:42:26.635 18302-26102/my.package I/StripeTerminal: class=RestClient message="url=https://api.stripe.com//v1/terminal/readers/discover status=OK headers=<HIDDEN>
2021-06-22 10:42:27.462 18302-20909/my.package I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: DISCOVER -> CANCELLED: null"
2021-06-22 10:42:27.465 18302-20922/my.package D/StripeTerminal: class=Terminal message=connectReader serial_number=WPC32302*******
2021-06-22 10:42:27.470 18302-26104/my.package E/DiscoveryCancelCallback: Cancelling Stripe readers discovery failed. com.stripe.stripeterminal.model.external.TerminalException: Operation completed before it could be canceled
        at com.stripe.stripeterminal.TerminalSession$CancelableOperation.onSuccess$terminalsdk_publish(TerminalSession.kt:406)
        at com.stripe.stripeterminal.TerminalSession$DiscoverReadersOperation.onSuccess$terminalsdk_publish(TerminalSession.kt:877)
        at com.stripe.stripeterminal.TerminalSession$DiscoverReadersOperation.run$terminalsdk_publish(TerminalSession.kt:863)
        at com.stripe.stripeterminal.TerminalSession$enqueueOperation$1.run(TerminalSession.kt:274)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2021-06-22 10:42:27.479 18302-20909/my.package I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
2021-06-22 10:42:27.479 18302-26104/my.package D/StripeTerminal: class=BbposAdapter message=connectReader
2021-06-22 10:42:27.479 18302-26104/my.package D/StripeTerminal: class=TerminalListenerProxy message=onConnectionStatusChange(CONNECTING)
2021-06-22 10:42:27.480 18302-20909/my.package D/DiscoveryCancelCallback: Cancelling Stripe readers discovery succeeded.
2021-06-22 10:42:27.486 18302-26104/my.package I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: EMPTY -> CONNECT: Connect requested"
2021-06-22 10:42:29.583 18302-18302/my.package I/StripeTerminal: class=BBPOSControllerListener message=onBTConnected
2021-06-22 10:42:29.587 18302-18302/my.package I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: CONNECT -> READER_INFO: null"
2021-06-22 10:42:30.044 18302-18302/my.package I/StripeTerminal: class=BBPOSControllerListener message="onReturnDeviceInfo <HIDDEN>
2021-06-22 10:42:30.053 18302-18302/my.package I/StripeTerminal: class=BbposAdapter reader_software_version=4.01.00.13-SZZZ_Prod_EU_W1_off_v9-510001 reader_battery_level=0.54
2021-06-22 10:42:30.053 18302-18302/my.package D/StripeTerminal: class=TerminalListenerProxy message=onConnectionStatusChange(CONNECTED)
2021-06-22 10:42:30.054 18302-18302/my.package I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: READER_INFO -> CANCELLED: null"
2021-06-22 10:42:30.054 18302-18302/my.package I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
2021-06-22 10:42:30.055 18302-26104/my.package D/StripeTerminal: class=ConnectionTokenManager message=refreshToken
2021-06-22 10:42:30.133 18302-26104/my.package I/StripeTerminal: class=RestClient message="url=https://api.stripe.com/v1/terminal/connection_tokens/activate request=<HIDDEN>
2021-06-22 10:42:30.380 18302-26075/my.package D/StripeTerminal: class=ConnectionTokenManager message=fetchConnectionToken.onSuccess
2021-06-22 10:42:31.331 18302-26104/my.package I/StripeTerminal: class=RestClient message="url=https://api.stripe.com/v1/terminal/connection_tokens/activate status=OK headers=<HIDDEN>
2021-06-22 10:42:31.340 18302-26104/my.package I/StripeTerminal: class=TerminalSession reader_id=tmr_EM0kLApSqmzGem
2021-06-22 10:42:31.340 18302-26104/my.package D/StripeTerminal: class=BbposAdapter message=checkForUpdate
2021-06-22 10:42:31.341 18302-26104/my.package I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: EMPTY -> CHECK_FOR_UPDATE: Check for update requested"
2021-06-22 10:42:31.416 18302-18302/my.package I/StripeTerminal: class=BBPOSControllerListener message=onReturnReadTerminalSettingResult
2021-06-22 10:42:33.900 18302-26102/my.package I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: CHECK_FOR_UPDATE -> CANCELLED: null"
2021-06-22 10:42:33.901 18302-26102/my.package I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
2021-06-22 10:42:33.902 18302-26104/my.package D/StripeTerminal: class=TerminalListenerProxy message=onPaymentStatusChange(READY)
2021-06-22 11:30:36.231 9651-16296/my.package D/ConnectReaderCallback: Reader connect success
```
and here are the logs when the connection "hangs":
```
2021-06-22 10:43:27.076 18302-18703/my.package D/StripeTerminal: class=Terminal message=discoverReaders
2021-06-22 10:43:27.077 18302-26104/my.package D/StripeTerminal: class=BbposAdapter message=discoverReaders
2021-06-22 10:43:27.078 18302-26104/my.package I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: EMPTY -> DISCOVER: Discovery requested"
2021-06-22 10:43:27.210 18302-26102/my.package D/StripeTerminal: class=ApiClient message=discoverLocations
2021-06-22 10:43:27.214 18302-26102/my.package I/StripeTerminal: class=RestClient message="url=https://api.stripe.com//v1/terminal/readers/discover request={"readers":["WPC3230*******"]}"
2021-06-22 10:43:27.859 18302-26102/my.package I/StripeTerminal: class=RestClient message="url=https://api.stripe.com//v1/terminal/readers/discover status=OK headers=<HIDDEN>
2021-06-22 10:43:31.350 18302-20908/my.package I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: DISCOVER -> CANCELLED: null"
2021-06-22 10:43:31.350 18302-18703/my.package D/StripeTerminal: class=Terminal message=connectReader serial_number=WPC3230*******
2021-06-22 10:43:31.352 18302-26104/my.package E/MyDiscoveryCancelCallback: Cancelling Stripe readers discovery failed. com.stripe.stripeterminal.model.external.TerminalException: Operation completed before it could be canceled
        at com.stripe.stripeterminal.TerminalSession$CancelableOperation.onSuccess$terminalsdk_publish(TerminalSession.kt:406)
        at com.stripe.stripeterminal.TerminalSession$DiscoverReadersOperation.onSuccess$terminalsdk_publish(TerminalSession.kt:877)
        at com.stripe.stripeterminal.TerminalSession$DiscoverReadersOperation.run$terminalsdk_publish(TerminalSession.kt:863)
        at com.stripe.stripeterminal.TerminalSession$enqueueOperation$1.run(TerminalSession.kt:274)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2021-06-22 10:43:31.356 18302-26104/my.package D/StripeTerminal: class=BbposAdapter message=connectReader
2021-06-22 10:43:31.356 18302-26104/my.package D/StripeTerminal: class=TerminalListenerProxy message=onConnectionStatusChange(CONNECTING)
2021-06-22 10:43:31.361 18302-20908/my.package I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
2021-06-22 10:43:31.362 18302-20908/my.package D/MyDiscoveryCancelCallback: Cancelling Stripe readers discovery succeeded.
```
Please note that I have hidden some information I have considered sensitive and replaced them with `<HIDDEN>`

## Code to reproduce
It's kind of difficult to prepare a small repository for the issue, since as far as I know connecting to the terminal requires integration with the backend (so that we can obtain connection-token). However, here is just a brief wrapped code sample I've been using:
```
        val config = DiscoveryConfiguration(
            10 * 60 * 1000,
            DiscoveryMethod.BLUETOOTH_SCAN,
            false
        )
        var discoveryCancelable: Cancelable? = null
        discoveryCancelable = Terminal.getInstance().discoverReaders(config, object : DiscoveryListener {
            override fun onUpdateDiscoveredReaders(readers: List<Reader>) {
                readers.firstOrNull()?.let { reader ->
                    discoveryCancelable?.cancel(object: Callback {
                        override fun onSuccess() {
                            Log.d("DiscoveryCancelCallback", "Cancelling Stripe readers discovery succeeded.")
                        }

                        override fun onFailure(e: TerminalException) {
                            Log.e("DiscoveryCancelCallback", "Cancelling Stripe readers discovery failed.", e)
                        }
                    })
                    Terminal.getInstance().connectBluetoothReader(
                        reader = reader,
                        config = ConnectionConfiguration.BluetoothConnectionConfiguration(),
                        listener = object: BluetoothReaderListener {},
                        connectionCallback = object: ReaderCallback {
                            override fun onSuccess(reader: Reader) {
                                Log.d("ConnectReaderCallback", "Reader connect success")
                            }

                            override fun onFailure(e: TerminalException) {
                                Log.e("ConnectReaderCallback", "Reader connect failure", e)
                            }
                        }
                    )
                }
            }
        }, object : Callback {
            override fun onSuccess() {
                Log.d("DiscoveryCallback", "Discovery success")
            }

            override fun onFailure(e: TerminalException) {
                Log.e("DiscoveryCallback", "Discovery success", e)
            }
        })
```

## Android version
Android 7.1.2, Android 9, Android 10

## Impacted devices (Android devices or readers)
Android devices: Samsung Tab A 2019 SM-T510, Samsung Tab A 2019 SM-T515, Sunmi T2s, Sunmi T2s Lite, Wintec Anypos 600, OnePlus 6T
Reader: WisePad 3

## SDK version
2.0.0-b3 (`com.stripe:stripeterminal:2.0.0-b3`)

## Other information
Please let me know if I can assist in providing more details regarding this issue.

**Comment by danwaters-stripe** [comment] 2021-06-28 18:40
I haven't had a chance to try replicating this yet, but I believe the issue is that you're both calling `cancel` on the `discoveryCancelable` _and_ calling `Terminal.getInstance().connectBluetoothReader`. `connectBluetoothReader` actually cancels the discovery internally, so there's no need to call both. I'm guessing there's some race condition where it's being doubly cancelled and not handling the resultant error correctly. 

We'll make sure to look into the race condition, but removing `discoveryCancelable.cancel` from your code entirely should solve your problem!

**Comment by chr-stripe** [comment] 2022-08-08 17:52
@Milszym can you confirm that after removing the redundant `discoveryCancelable?.cancel(...)` call, you're no longer experiencing any connection hangs? If so, I'll close this ticket out as it seems that your issue would be solved!

**Comment by chr-stripe** [comment] 2022-08-26 20:35
Closing due to inactivity. @Milszym if you're still running into this issue please feel free to re-open it or file a new one!

**Closed by chr-stripe** 2022-08-26 20:35 UTC
