### ISSUE TITLE
Not able to get a timeout for retrieving payment intent 

### ISSUE THREAD

**Issue by L-is-0** [stripe/stripe-terminal-android#290] opened 2023-02-07 13:36 UTC
## Summary
Hi, I am creating payment intent from server side and retrieving it by calling Terminal.getInstance().retrievePaymentIntent
However there are some of my devices not able to get any timeout exceptions from this retrieve payment intent request when network is poor. Can you please provide any solutions so user won't get stuck in the infinite loop?

## Android version
Android 11

## Impacted devices (Android devices or readers)
Tap to pay, simulated reader 

## SDK version
33

**Comment by L-is-0** [comment] 2023-03-01 11:19
Hi @chr-stripe sorry for chasing, but do we have any update on this issue, it seems to happened a lot for us in version 2.16.0-b1

**Comment by chr-stripe** [comment] 2023-03-02 19:02
Sorry @L-is-0, this issue seemed to slip through the cracks! Apologize for the delay here.

> Some of my devices not able to get any timeout exceptions from this retrieve payment intent request when network is poor

Just to clarify, what is the behaviour when you're calling this method during a poor network connection state? Is it hanging indefinitely?

**Comment by L-is-0** [comment] 2023-03-09 13:56
Hi @chr-stripe , thanks for getting back. The app wasn't able to get anything from the SDK and just hanging there for 3-4 minutes until we restart the hardware. We checked the logs of the device, looks like there is no response or even failed/timeout message were returned after the app made request to Terminal.getInstance().retrievePaymentIntent.

**Comment by chr-stripe** [comment] 2023-03-09 17:23
Was your app doing anything else with the Terminal SDK at the time you called `retrievePaymentIntent()`? For example, did you have an active `collectPaymentIntent()` running when you called that, or were you interacting with the reader in any way when you tried to retrieve the payment intent?

**Comment by Jason-IUVO** [comment] 2023-03-21 07:14
I encountered the same problem. When re retrievePaymentIntent() is called, the SDK will not call back successful or failed methods, and any operation of the card reader is still unresponsive.
I'm using an M2 card reader on Android.

**Comment by chr-stripe** [comment] 2023-03-27 22:59
Hi folks, for anyone reporting that `retrievePaymentIntent()` is not calling any callbacks, please provide the following information to help us diagnose this:

1. Any device logs from your application leading up to the issue
2. Were there any interactions with the Terminal SDK (eg: `collectPaymentMethod`, `processPayment`, etc) prior to calling `retrievePaymentIntent()`?
3. What kind of reader were you connected to? Can you provide a reader serial number?

**Comment by L-is-0** [comment] 2023-04-03 13:20
hi @chr-stripe apologise for getting back to this late. 

1. Any device logs from your application leading up to the issue
    - I don't have the full logs for this issue unfortunately as it's a bit tricky to replicate, however it did happen to me for a few times. We have logs from the retrievePaymentIntent() request, so we should see either success or failure after the app made request, but we didn't see any response from it. 
2. Were there any interactions with the Terminal SDK (eg: collectPaymentMethod, processPayment, etc) prior to calling retrievePaymentIntent()?
   - the flow we have in the app is: generating the payment intent from our backend server -> calling retrievePaymentIntent -> collectPayment -> processPayment 
3. What kind of reader were you connected to? Can you provide a reader serial number?
    - it is tap to pay simulated reader

**Comment by chance-yang** [comment] 2023-05-06 09:26
Hi,I encountered the same problem. When retrievePaymentIntent() is called, the SDK will not call back successful or failed methods. 
I‘m using an M2(STRM26232029849) card reader on Android 9.0,using usb connection.
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/25995306/236615640-6e87a44b-0790-4dc3-8622-428829513a3b.png">
stripe sdk: "com.stripe:stripeterminal:3.0.0-b1"

**Comment by chr-stripe** [comment] 2023-05-31 00:04
Hi folks, I believe this may be fixed by some changes in the upcoming `2.21.0` SDK release. I'll ping in this issue once it's available for you to test and verify if it no longer occurs.

**Comment by chr-stripe** [comment] 2023-06-06 19:30
Terminal SDK `2.21.0` is available, please try this version out to see if you're no longer able to reproduce the reported issue. Thanks!

**Comment by JessieLau-CT** [comment] 2023-06-07 06:06
![image](https://github.com/stripe/stripe-terminal-android/assets/59676668/c9b8912d-cbf7-47c8-bc2e-961e87148fec)
Hi, I have the same issue. And I upgraded @stripe/stripe-terminal-react-native to 0.0.1-beta.12. Android SDK patch to "2.21.0". A USB connection and immediate disconnection occurred.

**Comment by chr-stripe** [comment] 2023-06-27 23:34
Closing this issue since we believe it has been resolved, but if anyone encounters this on SDK `2.21.0` please feel free to comment with a reader serial number + logs and we will investigate further.

**Closed by chr-stripe** 2023-06-27 23:34 UTC
Labels: bug
