### ISSUE TITLE
TerminalException: Transaction timed out.  the USB connected card reader

### ISSUE THREAD

**Issue by KoRyou** [stripe/stripe-terminal-android#402] opened 2023-11-20 08:42 UTC
## Summary

As shown in the log, after setting up the payment intent, a “TerminalException: Transaction timed out.” was returned. The network is normal and the card reader did not receive a disconnection callback.This card reader has this problem several times a day.
 I also received a callback of Transaction timed out. in another way: unplugging the USB connected card reader before calling collectPaymentMethod(). 
Please tell me what went wrong and how to avoid this situation.

## Code to reproduce

**Log**
[2023-11-17 16:27:58.301][ INFO ]BBPos device, device response:paymentIntent() to set payment intent - pi_3ODZa2HnmbEF7f1O02pp6LTe_secret_g6GUdTWLoFwADcP2ulaHlk8kG
[2023-11-17 16:27:58.542][ INFO ]BBPos device, device response:payment intent ID successful - pi_3ODZa2HnmbEF7f1O02pp6LTe
[2023-11-17 16:27:58.554][ INFO ]BBPos device, device response:payment status changed - WAITING_FOR_INPUT
[2023-11-17 16:27:58.582][ INFO ]BBPos device, (onRequestReaderInput) device response: waiting for card swipe or insertion
[2023-11-17 16:27:58.595][ INFO ]bbPosSwipeCard - Swipe / Insert / Tap
[2023-11-17 16:28:58.614][ INFO ] User clicked cancel or timed out and cancelled the order
[2023-11-17 16:28:58.628][ INFO ]BBPos device, device response:payment status changed - READY
[2023-11-17 16:28:58.643][ INFO ]BBPos device, device response:payment cancellation successful
[2023-11-17 16:29:28.697][ WARN ]BBPos device, device response:payment collection failed - **com.stripe.stripeterminal.external.models.TerminalException: Transaction timed out.**
[2023-11-17 16:29:28.715][ ERROR ]bbPosPayFail-Payment failure:USER_ERROR.CARD_READ_TIMED_OUT

## Android version

android 7.1.2
## Impacted devices (Android devices or readers)

Connection method ： USB
STRM26229002959   

## SDK version

com.stripe:stripeterminal:2.21.1

**Comment by chr-stripe** [comment] 2023-12-19 06:48
Hi @KoRyou, can you see if you can still reproduce this with the version `3.2.1` that we released today? I believe we may have addressed this issue in that version.

**Comment by KoRyou** [comment] 2024-01-08 08:09
🙏Thank you for your answer @chr-stripe , Our device is running on Android 7.1 system, but the strip3.2.1 version requires Android 8 or above. Can it be fixed on the 2.x.x version?  Is there any other solution?

**Comment by chr-stripe** [comment] 2024-01-18 00:41
Hi @KoRyou, currently we are actively maintaining the latest 3.X SDK versions and only providing support for critical fixes and security updates in the latest 2.X versions. We will investigate adding the fix for this in the next 2.X maintenance release but we don’t have a concrete timeframe on when this would be available.

Are you looking into dropping support for Android 7.0 and 7.1 devices soon? Please refer to our [SUPPORT.md](https://github.com/stripe/stripe-terminal-android/blob/master/SUPPORT.md) documentation for the latest information on 2.X support timelines.

**Comment by KoRyou** [comment] 2024-01-18 01:47
Thank you @chr-stripe , All of our customized devices are still running on the Android 7.1 system, and we cannot give up support at present. We look forward to Strip's 2.x version.

**Comment by billfinn-stripe** [comment] 2024-04-10 00:37
Hi @Oshariser -- we do not have any update on 2.X maintenance release scheduling nor if we'll include this issue in the next 2.X maintenance release.

**Comment by whyteH** [comment] 2024-05-14 01:05
Hello, when this exception occurs, the SDK will use ReaderReconnectionListener to reconnect, but sometimes it will not be connected directly. After disconnectReader, it will not work again through the POS connection process. It can only be done by powering off and restarting. Is there any other better method? solution?

**Comment by whyteH** [comment] 2024-05-14 01:07
Hello, when this exception occurs, the SDK will use ReaderReconnectionListener to reconnect, but sometimes it will not be connected directly. After disconnectReader, it will not work again through the POS connection process. It can only be done by powering off and restarting. In version 2.x , is there any solution that can connect without power interruption?

**Comment by xiaoshen-stripe** [comment] 2024-10-29 05:02
Hi there,
We have released our final SDK V2 version [0], which includes our best effort to address this issue. 
However, please note that this is the last release for SDK V2, and the Terminal Android SDK V2 has now reached its end of support [1]. This means it will no longer receive any necessary updates or fixes to ensure continued functionality.

To avoid any interruptions, we strongly encourage you to upgrade to SDK V3 or higher.  Thank you.

[0] https://github.com/stripe/stripe-terminal-android/blob/master/CHANGELOG.md#2234---2024-10-24
[1] https://github.com/stripe/stripe-terminal-android/blob/master/SUPPORT.md#end-of-life-eol

**Closed by xiaoshen-stripe** 2024-10-29 05:02 UTC

**Comment by KoRyou** [comment] 2024-10-29 08:43
Received, thank you for releasing the new version.




赵武灵王
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stripe/stripe-terminal-android"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月29日(星期二) 中午1:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [stripe/stripe-terminal-android] TerminalException: Transaction timed out.  the USB connected card reader (Issue #402)





 
Hi there,
 We have released our final SDK V2 version [0], which includes our best effort to address this issue.
 However, please note that this is the last release for SDK V2, and the Terminal Android SDK V2 has now reached its end of support [1]. This means it will no longer receive any necessary updates or fixes to ensure continued functionality.
 
To avoid any interruptions, we strongly encourage you to upgrade to SDK V3 or higher.  Thank you.
 
[0] https://github.com/stripe/stripe-terminal-android/blob/master/CHANGELOG.md#2234---2024-10-24
 [1] https://github.com/stripe/stripe-terminal-android/blob/master/SUPPORT.md#end-of-life-eol

**Comment by 007xiaoyang** [comment] 2024-12-17 15:50
Hello, I am unable to download the 2.23.4 version dependency using Gradle. Do you know the reason for this?

**Comment by xiaoshen-stripe** [comment] 2024-12-18 03:50
> Hello, I am unable to download the 2.23.4 version dependency using Gradle. Do you know the reason for this?

Hi there, we've tested this and were able to download the v2.34.4 dependency without issues. We can confirm that it is available on Maven Central, so if you can please try again by clearing your Gradle cache and syncing your project again. Thanks.

**Comment by 007xiaoyang** [comment] 2024-12-18 16:22
> > Hello, I am unable to download the 2.23.4 version dependency using Gradle. Do you know the reason for this?
> 
> Hi there, we've tested this and were able to download the v2.34.4 dependency without issues. We can confirm that it is available on Maven Central, so if you can please try again by clearing your Gradle cache and syncing your project again. Thanks.

Just clear the cache, thank you
