### ISSUE TITLE
An ANR issue on SDK 2.9.0

### ISSUE THREAD

**Issue by minjie0707** [stripe/stripe-terminal-android#235] opened 2022-06-10 13:43 UTC
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/82426849/173078835-e431de73-0723-4cd7-8acf-9ced4add8b64.png">

**Comment by justinadkins** [comment] 2022-07-10 17:39
I'm also experiences ANR issues due to `com.stripe.stripeterminal.transaction.TransactionStateMachine.update` on SDK 2.7.1.

**Comment by justinadkins** [comment] 2022-08-10 18:59
Still seeing on 2.12.0

**Comment by chr-stripe** [comment] 2022-08-10 19:10
Hi @minjie0707 + @justinadkins! Can you provide a bit more diagnostic info as to how you're able to experience this ANR using [our issue template](https://github.com/stripe/stripe-terminal-android/issues/new?assignees=&labels=&template=terminal-android-sdk-issue.md&title=)?

Are you able to reproduce this consistently under certain conditions, or does it only show up randomly?

**Comment by justinadkins** [comment] 2022-08-10 21:47
## Summary
In the past 14 days, 12.57% of our device fleet has experienced 207 ANR events sourced to `com.stripe.stripeterminal.transaction.TransactionStateMachine.update`.

## Code to reproduce
N/A

## Android version
Android 7.1.2, 9, 10

## Impacted devices (Android devices or readers)
All our readers are `BBPOS Chipper 2X`. The majority of the impacted devices are `TES (Touch Embedded Solutions) igs-series-gen2`, we have also seen these errors on `Lenovo XiaoXin Pad` and `Elo-i2-22Std`.

## SDK version
2.7.1, 2.12.0

## Other information
Stack trace from one of our devices:
<img width="795" alt="Screen Shot 2022-08-10 at 3 46 27 PM" src="https://user-images.githubusercontent.com/100159094/184026266-43abce62-6b89-4f66-86e0-d26dec676085.png">

**Comment by chr-stripe** [comment] 2022-08-11 15:10
@justinadkins when you receive the ANR, do you only get the stack trace of the main thread, or would you happen to also have the trace dump of all threads that are running/waiting at the time of the ANR also handy?

**Comment by justinadkins** [comment] 2022-08-12 02:06
@chr-stripe We only get this main thread stack trace. This is surfaced by a data platform we use called Embrace. Is there somewhere we could add a log to assist in debugging?

**Comment by chr-stripe** [comment] 2022-08-12 02:51
I'm not sure how your application is being distributed, but if you have access to the Google Play Console, I _believe_ it lists all threads under **Android Vitals > Crashes and ANRs**. I have a rough idea of what might be happening and I will try to set aside some time tomorrow to attempt to reproduce.

Have you been able to reproduce this locally, or only observed through ANR reports via Embrace?

**Comment by justinadkins** [comment] 2022-08-12 05:47
Unfortunately our app isn't on Google Play. I haven't been able to reproduce locally, only what we see on Embrace. They do provide this flame graph, not sure if it's much use to you.

<img width="1777" alt="Screen Shot 2022-08-11 at 11 40 34 PM" src="https://user-images.githubusercontent.com/100159094/184292056-96ed7c43-c02d-4e50-aabb-8e8c6d8e51d7.png">

**Comment by justinadkins** [comment] 2022-08-12 06:00
I just manually went through 8 session logs where this occurred and 6 of them had emitted `MULTIPLE_CONTACTLESS_CARDS_DETECTED` right before the ANR event.

**Comment by chr-stripe** [comment] 2022-08-12 14:03
That's helpful, thanks! And very suspicious indeed. If you're able to share any session logs that would be great as well. Either way I'm currently attempting to reproduce this on my side.

**Comment by justinadkins** [comment] 2022-08-15 14:50
Any luck reproducing? My session logs probably aren't the most useful. Here's an example.
<img width="1487" alt="Screen Shot 2022-08-15 at 8 47 33 AM" src="https://user-images.githubusercontent.com/100159094/184658106-3806181d-3cf0-4bba-8160-2505203e581e.png">

I'd be happy to sync / schedule a meeting to walk you through some of these if that would help.

**Comment by chr-stripe** [comment] 2022-08-22 16:35
I've still not been able to reproduce this, but I think we have identified a fix for this issue that will now make sure that this method won't be called on the main thread anymore. As a result, _if_ `TransactionStateMachine.update()` ends up taking a while, it shouldn't be incurring an ANR anymore since it'll be off the main thread.

Unfortunately I _don't_ think I was able to get this change into the 2.13.0 release cycle, so we may have to wait until 2.14.0 for this fix to be released.

**Comment by justinadkins** [comment] 2022-08-22 16:40
Thanks for the update @chr-stripe!

**Comment by justinadkins** [comment] 2022-10-04 14:55
@chr-stripe any update on when the fix you mentioned will be released? I see `2.14.0` went out but no mention of this in the changelog.

**Comment by chr-stripe** [comment] 2022-10-11 17:51
It should be present in the `2.14.0` release despite no mention in the CHANGELOG. Are you able to update to this latest version and verify if you're still getting ANRs like this in your app?

**Comment by justinadkins** [comment] 2022-10-11 19:08
Thank you @chr-stripe, I'll prioritize getting the version bump in our next release.

**Comment by chr-stripe** [comment] 2022-11-01 15:57
@justinadkins any updates on how the version bump has gone? Are you still seeing this issue?

**Comment by chr-stripe** [comment] 2022-12-08 01:37
Spoke offline and it appears that the fix in 2.14.0 has resolved this ANR.

**Closed by chr-stripe** 2022-12-08 01:37 UTC
